#!/usr/bin/env python3
"""
.claude/pipeline/tools/package.py — the pipeline package: publish, install,
refresh, upgrade, check, shape (ADR-0092 D1-D5).

This is the ONE implementation of PACKAGE-INTEGRITY. `dashboard/health.py`
registers a delegating row over it (ADR-0064 D3), and CI CHECK 30 (or the
next free CHECK number) consumes that row. `package.py check` runs the same
arms directly, so a host can run it before and without `dashboard/`.

Roots: this module NEVER derives the repository or package root from its
own `__file__` location (that is the self-location arm's own subject). It
imports the sibling `pipeline_config` module via a `sys.path` insertion
(ADR-0092 D1 "Roots" blesses this — a `sys.path` entry binds no name), then
asks it for `repo_root()` / `package_root()` / `mode()` like every other
caller must.

Subcommands:
  publish <X.Y.Z>              home only
  install --source U [--integration I --release R]   post-subtree-add wiring
  refresh                      regenerate shims
  upgrade <vX.Y.Z>             host only
  check                        run every in-scope arm
  shape <rev>                  squash-shape predicate (exit 0 iff squash-shape)

Refusal contract (ADR-0092 D3): every refusal prints
  package.py: refused (<cause>): <detail>
to stderr and exits non-zero BEFORE any write. Cause tokens are fixed.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

# --- Sibling import (ADR-0092 D1 "Roots": a sys.path insertion is blessed;
# it binds no name, so it is not a self-location arm subject). ---
sys.path.insert(0, str(Path(__file__).resolve().parent))
import pipeline_config as pc  # noqa: E402

# This tool's own output (and the subprocess output it re-prints from
# fresh-process `refresh`/`check` calls) may carry non-ASCII text; force
# UTF-8 on stdout/stderr so a Windows host's cp1252 console never crashes
# printing it (a `capture_output=True` pipe otherwise falls back to the
# platform's locale encoding).
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")
_TAG_RE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")
_SUBTREE_PREFIX = ".claude/pipeline"
_GENERATED_MARKER_PREFIX = "GENERATED by .claude/pipeline/tools/package.py refresh from "
_IMPORT_LINE = "@.claude/pipeline/CLAUDE.md"


class Refused(Exception):
    def __init__(self, cause: str, detail: str):
        super().__init__(f"package.py: refused ({cause}): {detail}")
        self.cause = cause
        self.detail = detail


def _refuse(cause: str, detail: str):
    raise Refused(cause, detail)


def _run(args, cwd, check=True):
    result = subprocess.run(
        args, cwd=str(cwd), capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    if check and result.returncode != 0:
        raise RuntimeError(
            f"command failed ({result.returncode}): {' '.join(args)}\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}"
        )
    return result


def _git(args, cwd, check=True):
    return _run(["git"] + args, cwd, check=check)


def _is_dirty(repo_root: Path) -> bool:
    out = _git(["status", "--porcelain"], repo_root).stdout
    return bool(out.strip())


def _version_key(text: str):
    m = _VERSION_RE.match(text)
    if not m:
        return None
    return tuple(int(x) for x in m.groups())


def _tag_key(tag: str):
    m = _TAG_RE.match(tag)
    if not m:
        return None
    return tuple(int(x) for x in m.groups())


def _newest_version_tag(repo_root: Path):
    """Newest local+remote `v*` tag matching ^v\\d+\\.\\d+\\.\\d+$, or None."""
    local = _git(["tag", "-l", "v*"], repo_root).stdout.splitlines()
    remote_raw = _run(
        ["git", "ls-remote", "--tags", "origin"], repo_root, check=False
    ).stdout.splitlines()
    remote = [line.rsplit("refs/tags/", 1)[-1] for line in remote_raw if "refs/tags/" in line]
    candidates = [t for t in (local + remote) if _tag_key(t) is not None]
    if not candidates:
        return None
    return max(candidates, key=_tag_key)


def _read_version(pkg_root: Path) -> str:
    version_file = pkg_root / "VERSION"
    if not version_file.exists():
        return ""
    return version_file.read_text(encoding="utf-8").strip()


# ---------------------------------------------------------------------------
# Squash shape (ADR-0092 D3)
# ---------------------------------------------------------------------------

def _commit_message(rev: str, repo_root: Path) -> str:
    return _git(["log", "-n1", "--format=%B", rev], repo_root).stdout


def _split_sha(message: str):
    m = re.search(r"^git-subtree-split:\s*([0-9a-f]{40})\s*$", message, re.MULTILINE)
    return m.group(1) if m else None


def shape(rev: str, repo_root: Path) -> tuple[bool, str]:
    """Squash-shape predicate (ADR-0092 D3). Returns (is_shape, note)."""
    message = _commit_message(rev, repo_root)
    if f"git-subtree-dir: {_SUBTREE_PREFIX}" not in message:
        return False, "no git-subtree-dir trailer"
    split = _split_sha(message)
    if split is None:
        return False, "no git-subtree-split trailer"
    if re.search(r"^git-subtree-mainline:", message, re.MULTILINE):
        return False, "has git-subtree-mainline trailer"

    tree = _git(["rev-parse", f"{rev}^{{tree}}"], repo_root).stdout.strip()
    split_exists = _run(["git", "cat-file", "-e", split], repo_root, check=False).returncode == 0
    if split_exists:
        split_tree = _git(["rev-parse", f"{split}^{{tree}}"], repo_root).stdout.strip()
        if tree != split_tree:
            return False, "tree != split tree"
        note = "tree==split-tree"
    else:
        # Clause 2 fallback (ADR-0092 D3): the split commit is absent (a
        # fresh clone never has it). Evaluate the tree's own shape instead:
        # a package root has VERSION and no .claude entry.
        ls = _git(["ls-tree", "--name-only", tree], repo_root).stdout.splitlines()
        if "VERSION" not in ls or ".claude" in ls:
            return False, "split tree not local; tree-shape test failed"
        note = "split tree not local; tree-shape test"

    parents = _git(["log", "-n1", "--format=%P", rev], repo_root).stdout.split()
    if len(parents) == 0:
        return True, note + "; no parent (install squash)"
    if len(parents) > 1:
        return False, "more than one parent"
    parent_ok, parent_note = shape(parents[0], repo_root)
    if not parent_ok:
        return False, f"parent not squash-shape ({parent_note})"
    return True, note + "; parent squash-shape"


def cmd_shape(argv, repo_root: Path) -> int:
    if len(argv) != 1:
        print("usage: package.py shape <rev>", file=sys.stderr)
        return 2
    ok, note = shape(argv[0], repo_root)
    print(f"{'PASS' if ok else 'FAIL'}: shape({argv[0]}) — {note}")
    return 0 if ok else 1


# ---------------------------------------------------------------------------
# Pristine (ADR-0092 D3)
# ---------------------------------------------------------------------------

def pristine(repo_root: Path) -> tuple[bool, str]:
    found = _run(
        ["git", "log", "-n1", "--format=%H", "--grep=^git-subtree-dir: " + re.escape(_SUBTREE_PREFIX) + "$",
         "HEAD"],
        repo_root, check=False,
    ).stdout.strip()
    if not found:
        return False, "no subtree-trailer commit reachable from HEAD"
    ok, note = shape(found, repo_root)
    if not ok:
        return False, f"newest subtree commit {found[:12]} not squash-shape ({note})"
    head_tree = _git(["rev-parse", f"HEAD:{_SUBTREE_PREFIX}"], repo_root, check=False).stdout.strip()
    commit_tree = _git(["rev-parse", f"{found}^{{tree}}"], repo_root).stdout.strip()
    if not head_tree or head_tree != commit_tree:
        return False, "HEAD:.claude/pipeline != newest subtree commit's tree"
    return True, "ok"


# ---------------------------------------------------------------------------
# Shims (ADR-0092 D2) — this slice: skills/grill-me/ only.
# ---------------------------------------------------------------------------

# (package-relative source, repo-relative shim path)
_SHIM_SPECS = [
    ("skills/grill-me/SKILL.md", ".claude/skills/grill-me/SKILL.md"),
]

_LINK_RE = re.compile(r"(\[[^\]]*\]\()([^)\s]+)(\))")


def _rebase_links(text: str, source_path: Path, shim_path: Path) -> str:
    """Re-base relative Markdown link targets so each resolves to the same
    file it resolves to from `source_path` (ADR-0092 D2 transform 2)."""

    def _sub(m):
        prefix, target, suffix = m.group(1), m.group(2), m.group(3)
        if target.startswith(("http://", "https://", "#", "/")):
            return m.group(0)
        absolute = (source_path.parent / target).resolve()
        try:
            rel = os.path.relpath(absolute, start=shim_path.parent)
        except ValueError:
            return m.group(0)
        rel = rel.replace(os.sep, "/")
        return f"{prefix}{rel}{suffix}"

    return _LINK_RE.sub(_sub, text)


def _generated_marker_md(source_rel: str) -> str:
    return f"<!-- GENERATED by .claude/pipeline/tools/package.py refresh from {source_rel} -->"


def _has_generated_marker(text: str) -> str | None:
    """Returns the marker line if `text` opens with one (within the first
    handful of lines, after any frontmatter), else None."""
    lines = text.splitlines()
    # Skip a leading YAML frontmatter block.
    idx = 0
    if lines and lines[0].strip() == "---":
        for i in range(1, min(len(lines), 60)):
            if lines[i].strip() == "---":
                idx = i + 1
                break
    for line in lines[idx: idx + 3]:
        if _GENERATED_MARKER_PREFIX in line:
            return line
    return None


def _render_shim(source_text: str, source_rel: str, source_path: Path, shim_path: Path) -> str:
    """Apply the closed two-transform set (ADR-0092 D2) to `source_text`."""
    text = _rebase_links(source_text, source_path, shim_path)
    lines = text.splitlines(keepends=True)
    marker = _generated_marker_md(source_rel) + "\n"
    if lines and lines[0].strip() == "---":
        insert_at = None
        for i in range(1, min(len(lines), 60)):
            if lines[i].strip() == "---":
                insert_at = i + 1
                break
        if insert_at is not None:
            lines.insert(insert_at, marker)
            return "".join(lines)
    return marker + text


def _normalize_eol(text: str) -> str:
    return text.replace("\r\n", "\n")


def _shim_pairs(pkg_root: Path):
    for source_rel, shim_rel in _SHIM_SPECS:
        source_path = pkg_root / source_rel
        shim_path = pkg_root.parent.parent / shim_rel  # pkg_root = <repo>/.claude/pipeline
        yield source_rel, source_path, shim_path


def refresh(repo_root: Path, pkg_root: Path, write: bool = True) -> list[str]:
    """Regenerate every shim. Refuses (cause `collision`) before writing
    anything if a shim path holds a file without the generated marker.
    Returns the list of shim paths (repo-relative) that changed."""
    rendered = {}
    for source_rel, source_path, shim_path in _shim_pairs(pkg_root):
        if not source_path.exists():
            continue
        source_text = source_path.read_text(encoding="utf-8")
        rendered[shim_path] = _render_shim(source_text, source_rel, source_path, shim_path)

    # Collision refusal BEFORE any write.
    for shim_path, new_text in rendered.items():
        if shim_path.exists():
            existing = shim_path.read_text(encoding="utf-8")
            if _has_generated_marker(existing) is None:
                rel = shim_path.relative_to(repo_root)
                _refuse("collision", f"{rel} exists without the generated marker")

    changed = []
    for shim_path, new_text in rendered.items():
        existing = shim_path.read_text(encoding="utf-8") if shim_path.exists() else None
        if existing is None or _normalize_eol(existing) != _normalize_eol(new_text):
            changed.append(str(shim_path.relative_to(repo_root)))
            if write:
                shim_path.parent.mkdir(parents=True, exist_ok=True)
                shim_path.write_text(new_text, encoding="utf-8")
    return changed


# ---------------------------------------------------------------------------
# Layout arm
# ---------------------------------------------------------------------------

_REQUIRED_LAYOUT = ["VERSION", "CLAUDE.md", "tools/package.py"]

_SOFT_DEGRADE_GUARD_RE = re.compile(
    r'\[\s*!\s*-[fd]\s+"([^"]+)"\s*\]'
)


def _git_ls_files_count(repo_root: Path, pathspec: str) -> int:
    out = _git(["ls-files", "--", pathspec], repo_root, check=False).stdout
    return len([ln for ln in out.splitlines() if ln.strip()])


def _find_ci_checks_sh(repo_root: Path, pkg_root: Path) -> Path | None:
    """The soft-degrade guards live in ci-checks.sh, wherever it currently
    sits (root `tools/` until the slice that moves it; the package's own
    copy afterward). Preferring the package copy keeps this arm correct
    without a code change once `tools/` moves (ADR-0092 D1)."""
    pkg_copy = pkg_root / "tools" / "ci-checks.sh"
    if pkg_copy.exists():
        return pkg_copy
    root_copy = repo_root / "tools" / "ci-checks.sh"
    if root_copy.exists():
        return root_copy
    return None


def layout_arm(repo_root: Path, pkg_root: Path) -> list[str]:
    failures = []
    version_text = _read_version(pkg_root)
    if not _VERSION_RE.match(version_text):
        failures.append(f"(layout) VERSION missing or malformed: {version_text!r}")
    for rel in _REQUIRED_LAYOUT[1:]:
        if not (pkg_root / rel).exists():
            failures.append(f"(layout) required package member missing: {rel}")

    ci_checks = _find_ci_checks_sh(repo_root, pkg_root)
    if ci_checks is not None:
        text = ci_checks.read_text(encoding="utf-8", errors="replace")
        rel_ci = str(ci_checks.relative_to(repo_root))
        lines = text.splitlines()
        for i, line in enumerate(lines):
            m = _SOFT_DEGRADE_GUARD_RE.search(line)
            if not m:
                continue
            # Only a guard whose block prints a SKIP within the next few
            # lines is a soft-degrade guard (as opposed to an unrelated
            # negative-existence test).
            window = "\n".join(lines[i: i + 4])
            if "SKIP:" not in window:
                continue
            path = m.group(1)
            check_num_m = re.search(r"SKIP:\s*CHECK\s*(\S+)", window)
            check_label = check_num_m.group(1) if check_num_m else "?"
            target = (repo_root / path)
            if not target.exists():
                failures.append(
                    f"(layout) {rel_ci}:{i + 1} soft-degrade guard on missing "
                    f"path {path} (CHECK {check_label})"
                )
    return failures


# ---------------------------------------------------------------------------
# Self-location arm
# ---------------------------------------------------------------------------

_ROOT_NAME_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*ROOT[A-Za-z0-9_]*", re.IGNORECASE)


def self_location_arm(pkg_root: Path) -> list[str]:
    failures = []
    for path in sorted(pkg_root.rglob("*")):
        if not path.is_file():
            continue
        if path.name == "pipeline_config.py":
            continue
        if path.suffix not in (".py", ".sh") and "tools/pipe/" not in str(path).replace("\\", "/") \
                and "githooks/" not in str(path).replace("\\", "/"):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for lineno, line in enumerate(text.splitlines(), start=1):
            if "__file__" in line or "BASH_SOURCE" in line or re.search(r"\$0\b", line):
                # A root-shaped binding on this line, sourced from own
                # location. Skip the blessed sys.path insertion form.
                if "sys.path" in line:
                    continue
                assign_m = re.match(r"\s*([A-Za-z_][A-Za-z0-9_]*)\s*=", line)
                name = assign_m.group(1) if assign_m else ""
                def_m = re.match(r"\s*def\s+([A-Za-z_][A-Za-z0-9_]*)", line)
                if _ROOT_NAME_RE.search(name) or (def_m and "root" in def_m.group(1).lower()):
                    failures.append(f"(self-location) {path.name}:{lineno} root binding from own location")
    return failures


# ---------------------------------------------------------------------------
# Prompt-path arm
# ---------------------------------------------------------------------------

# Command-shaped token -> the pre-move root it names, read through
# ADR-0092 D1's rename map. Each is checked ONLY for a root that "counts as
# moved" (no tracked file remains at its pre-move location).
_PROMPT_PATH_PATTERNS = [
    (re.compile(r"(?<!\.claude/pipeline/)\b(?:python3?|bash)\s+tools/"), "tools"),
    (re.compile(r"(?<!\.claude/pipeline/)\btools/[\w./-]+\.(?:py|sh|txt)\b"), "tools"),
    (re.compile(r"(?<!\.claude/pipeline/)\btools/pipe/\w+"), "tools"),
    (re.compile(r"(?<!\.claude/pipeline/)\bdashboard/[\w./-]+\.py\b"), "dashboard"),
    (re.compile(r"(?<!\.claude/pipeline/)\bdashboard/fixtures/"), "dashboard"),
    (re.compile(r"(?<!\.claude/pipeline/)\bpytest\s+tests/"), "tests"),
    (re.compile(r"(?<!\.claude/pipeline/)\btests/[\w./-]+\.(?:py|txt)\b(?!::)"), "tests"),
    (re.compile(r"(?<!\.claude/pipeline/)\.githooks/"), ".githooks"),
    (re.compile(r"(?<!\.claude/pipeline/)\.claude/hooks/"), ".claude/hooks"),
    (re.compile(r"(?<!\.claude/pipeline/)\.claude/generated/"), ".claude/generated"),
    (re.compile(r"(?<!\.claude/pipeline/)\bbootstrap\.sh\b"), "bootstrap.sh"),
    (re.compile(r"(?<!\.claude/pipeline/)\bdocs/observability\.md\b"), "docs/observability.md"),
]

_SINGLE_FILE_ROOTS = {"bootstrap.sh", "docs/observability.md"}


def _root_has_moved(repo_root: Path, root: str) -> bool:
    if root in _SINGLE_FILE_ROOTS:
        return _git_ls_files_count(repo_root, root) == 0
    return _git_ls_files_count(repo_root, root + "/") == 0


def _prompt_path_subjects(repo_root: Path, pkg_root: Path) -> list[Path]:
    subjects = []
    for pattern in ("agents/*.md", "skills/*/SKILL.md", "CLAUDE.md",
                     "generated/*.md", "rules/*.md", "hooks/*", "githooks/*"):
        subjects.extend(sorted(pkg_root.glob(pattern)))
    if pc.mode(str(repo_root)) == "home":
        for rel in ("AGENTS.md",):
            p = repo_root / rel
            if p.exists():
                subjects.append(p)
        subjects.extend(sorted(repo_root.glob(".agents/skills/*/SKILL.md")))
        p = repo_root / "docs" / "openai-workflow.md"
        if p.exists():
            subjects.append(p)
    return [s for s in subjects if s.is_file()]


def prompt_path_arm(repo_root: Path, pkg_root: Path) -> list[str]:
    failures = []
    moved_cache: dict[str, bool] = {}
    for subject in _prompt_path_subjects(repo_root, pkg_root):
        text = subject.read_text(encoding="utf-8", errors="replace")
        rel = subject.relative_to(repo_root)
        for lineno, line in enumerate(text.splitlines(), start=1):
            for pattern, root in _PROMPT_PATH_PATTERNS:
                if not pattern.search(line):
                    continue
                if root not in moved_cache:
                    moved_cache[root] = _root_has_moved(repo_root, root)
                if moved_cache[root]:
                    failures.append(
                        f"(prompt-path) {rel}:{lineno} names moved root "
                        f"'{root}' without the .claude/pipeline/ prefix"
                    )
    return failures


# ---------------------------------------------------------------------------
# Currency arm
# ---------------------------------------------------------------------------

def currency_arm(repo_root: Path, pkg_root: Path) -> list[str]:
    failures = []
    for source_rel, source_path, shim_path in _shim_pairs(pkg_root):
        if not source_path.exists():
            continue
        expected = _render_shim(
            source_path.read_text(encoding="utf-8"), source_rel, source_path, shim_path
        )
        actual = shim_path.read_text(encoding="utf-8") if shim_path.exists() else None
        if actual is None:
            failures.append(f"(currency) {shim_path.relative_to(repo_root)} missing")
        elif _normalize_eol(actual) != _normalize_eol(expected):
            failures.append(f"(currency) {shim_path.relative_to(repo_root)} stale — run `pkg refresh`")

    claude_md = repo_root / "CLAUDE.md"
    text = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
    count = len([ln for ln in text.splitlines() if ln.strip() == _IMPORT_LINE])
    if count != 1:
        failures.append(f"(currency) root CLAUDE.md has {count} '{_IMPORT_LINE}' lines, expected 1")
    return failures


# ---------------------------------------------------------------------------
# check / arms dispatch
# ---------------------------------------------------------------------------

def run_arms(repo_root: Path, pkg_root: Path) -> list[tuple[str, bool, str]]:
    """Returns [(arm_name, ok, detail), ...] for every in-scope arm."""
    results = []
    mode = pc.mode(str(repo_root))

    for name, failures in (
        ("layout", layout_arm(repo_root, pkg_root)),
        ("self-location", self_location_arm(pkg_root)),
        ("prompt-path", prompt_path_arm(repo_root, pkg_root)),
        ("currency", currency_arm(repo_root, pkg_root)),
    ):
        if failures:
            for f in failures:
                results.append((name, False, f))
        else:
            results.append((name, True, "ok"))

    if mode == "host":
        ok, note = pristine(repo_root)
        results.append(("pristine", ok, note))
    return results


def cmd_check(repo_root: Path, pkg_root: Path) -> int:
    results = run_arms(repo_root, pkg_root)
    exit_code = 0
    for name, ok, detail in results:
        if ok:
            print(f"PASS: {name} — {detail}")
        else:
            print(f"FAIL: {name} — {detail}")
            exit_code = 1
    return exit_code


# ---------------------------------------------------------------------------
# refresh subcommand
# ---------------------------------------------------------------------------

def cmd_refresh(repo_root: Path, pkg_root: Path) -> int:
    changed = refresh(repo_root, pkg_root, write=True)
    for c in changed:
        print(f"refreshed: {c}")
    if not changed:
        print("refresh: nothing changed")
    return 0


# ---------------------------------------------------------------------------
# publish (ADR-0092 D3) — home only
# ---------------------------------------------------------------------------

def cmd_publish(argv, repo_root: Path, pkg_root: Path) -> int:
    if len(argv) != 1:
        print("usage: package.py publish X.Y.Z", file=sys.stderr)
        return 2
    version = argv[0]
    try:
        if pc.mode(str(repo_root)) != "home":
            _refuse("host-mode", "publish only runs in the home repository")
        if _is_dirty(repo_root):
            _refuse("dirty-tree", "working tree has uncommitted changes")
        current = _read_version(pkg_root)
        if current != version:
            _refuse("version-mismatch", f"VERSION is {current!r}, not {version!r}")
        tag = f"v{version}"
        existing_local = _git(["tag", "-l", tag], repo_root).stdout.strip()
        existing_remote = _run(["git", "ls-remote", "--tags", "origin", tag], repo_root, check=False).stdout.strip()
        if existing_local or existing_remote:
            _refuse("tag-exists", f"{tag} already exists")
        newest = _newest_version_tag(repo_root)
        if newest is not None and _version_key(version) <= _tag_key(newest):
            _refuse("not-newer", f"{version} is not newer than {newest}")
        release = pc.release_branch(str(repo_root))
        head = _git(["rev-parse", "HEAD"], repo_root).stdout.strip()
        is_ancestor = _run(
            ["git", "merge-base", "--is-ancestor", "HEAD", f"origin/{release}"], repo_root, check=False
        ).returncode == 0
        if not is_ancestor:
            _refuse("not-promoted", f"HEAD ({head[:12]}) is not reachable from origin/{release}")
    except Refused as r:
        print(str(r), file=sys.stderr)
        return 1

    split_sha = _git(["subtree", "split", f"--prefix={_SUBTREE_PREFIX}"], repo_root).stdout.strip()
    _git(["tag", "-a", tag, split_sha, "-m", f"pipeline {tag} (split from {head})"], repo_root)
    _git(["push", "origin", tag], repo_root)
    print(f"published {tag} at {split_sha[:12]} (split from {head[:12]})")
    return 0


# ---------------------------------------------------------------------------
# install (post-subtree-add wiring; ADR-0092 D3 steps 2-4) — run from the
# freshly-added copy, i.e. package.py already sits under .claude/pipeline/.
# ---------------------------------------------------------------------------

def cmd_install(argv, repo_root: Path, pkg_root: Path) -> int:
    source = None
    integration = None
    release = None
    i = 0
    while i < len(argv):
        if argv[i] == "--source" and i + 1 < len(argv):
            source = argv[i + 1]; i += 2
        elif argv[i] == "--integration" and i + 1 < len(argv):
            integration = argv[i + 1]; i += 2
        elif argv[i] == "--release" and i + 1 < len(argv):
            release = argv[i + 1]; i += 2
        else:
            i += 1
    if source is None:
        print("usage: package.py install --source <url> [--integration <b>] [--release <b>]", file=sys.stderr)
        return 2

    conf_path = repo_root / ".claude" / "pipeline.conf"
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    if conf_path.exists():
        lines = [ln for ln in conf_path.read_text(encoding="utf-8").splitlines()
                 if not ln.startswith("package_source=")
                 and not (integration and ln.startswith("integration_branch="))
                 and not (release and ln.startswith("release_branch="))]
    lines.append(f"package_source={source}")
    if integration:
        lines.append(f"integration_branch={integration}")
    if release:
        lines.append(f"release_branch={release}")
    conf_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    refresh(repo_root, pkg_root, write=True)

    claude_md = repo_root / "CLAUDE.md"
    text = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
    if _IMPORT_LINE not in text.splitlines():
        if text and not text.endswith("\n"):
            text += "\n"
        text += _IMPORT_LINE + "\n"
        claude_md.write_text(text, encoding="utf-8")

    version = _read_version(pkg_root)
    _git(["add", "-A"], repo_root)
    _git(["commit", "-q", "-m", f"chore(pipeline): wire v{version}"], repo_root, check=False)

    print("Next steps (run these yourself — install never pushes or bootstraps):")
    print("  git push")
    print("  bash .claude/pipeline/bootstrap.sh")
    return 0


# ---------------------------------------------------------------------------
# upgrade (ADR-0092 D3) — host only
# ---------------------------------------------------------------------------

def cmd_upgrade(argv, repo_root: Path, pkg_root: Path) -> int:
    if len(argv) != 1:
        print("usage: package.py upgrade vX.Y.Z", file=sys.stderr)
        return 2
    tag = argv[0]
    m = _TAG_RE.match(tag)
    if m is None:
        print(f"package.py: refused (not-newer): {tag!r} is not a version tag", file=sys.stderr)
        return 1
    try:
        if pc.mode(str(repo_root)) != "host":
            _refuse("home-mode", "upgrade only runs in a host")
        if _is_dirty(repo_root):
            _refuse("dirty-tree", "working tree has uncommitted changes")
        branch = _git(["symbolic-ref", "--short", "HEAD"], repo_root, check=False).stdout.strip()
        integration = pc.integration_branch(str(repo_root))
        release = pc.release_branch(str(repo_root))
        if branch and branch in (integration, release):
            _refuse("role-branch", f"current branch '{branch}' is a configured role")
        ok, note = pristine(repo_root)
        if not ok:
            _refuse("not-pristine", note)
        current = _read_version(pkg_root)
        current_key = _version_key(current) or (0, 0, 0)
        if _tag_key(tag) <= current_key:
            _refuse("not-newer", f"{tag} is not newer than installed {current}")
    except Refused as r:
        print(str(r), file=sys.stderr)
        return 1

    source = pc.package_source(str(repo_root))
    _git(["subtree", "pull", f"--prefix={_SUBTREE_PREFIX}", source, tag, "--squash",
          "-m", f"chore(pipeline): upgrade to {tag}"], repo_root)

    # Fresh process for refresh (ADR-0092 D3 step 2).
    refresh_result = subprocess.run(
        [sys.executable, str(pkg_root / "tools" / "package.py"), "refresh"],
        cwd=str(repo_root), capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    print(refresh_result.stdout, end="")
    if refresh_result.returncode == 0 and "refreshed:" in refresh_result.stdout:
        _git(["add", "-A"], repo_root)
        _git(["commit", "-q", "-m", f"chore(pipeline): refresh shims for {tag}"], repo_root, check=False)

    # Fresh process for check (ADR-0092 D3 step 3).
    check_result = subprocess.run(
        [sys.executable, str(pkg_root / "tools" / "package.py"), "check"],
        cwd=str(repo_root), capture_output=True, text=True,
        encoding="utf-8", errors="replace",
    )
    print(check_result.stdout, end="")
    if check_result.returncode != 0:
        print(check_result.stderr, file=sys.stderr)
        return check_result.returncode
    print(f"upgraded to {tag}")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    argv = list(argv if argv is not None else sys.argv[1:])
    if not argv:
        print("usage: package.py publish|install|refresh|upgrade|check|shape ...", file=sys.stderr)
        return 2
    cmd, rest = argv[0], argv[1:]
    repo_root = pc.repo_root()
    pkg_root = pc.package_root()

    if cmd == "publish":
        return cmd_publish(rest, repo_root, pkg_root)
    if cmd == "install":
        return cmd_install(rest, repo_root, pkg_root)
    if cmd == "refresh":
        return cmd_refresh(repo_root, pkg_root)
    if cmd == "upgrade":
        return cmd_upgrade(rest, repo_root, pkg_root)
    if cmd == "check":
        return cmd_check(repo_root, pkg_root)
    if cmd == "shape":
        return cmd_shape(rest, repo_root)
    print(f"usage: unknown subcommand {cmd!r}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
