#!/bin/sh
# .claude/pipeline/install.sh — install the pipeline package into a host
# (ADR-0092 D3). Run from the root of the repository being installed into.
#
# Usage:
#   bash .claude/pipeline/install.sh --source <url> --tag vX.Y.Z \
#       [--integration <branch>] [--release <branch>]
#
# Refuses BEFORE any write when:
#   - the working tree has uncommitted changes                -> dirty-tree
#   - the repository already holds .claude/pipeline/ without a
#     package_source (the home repository)              -> home-repository
#   - the repository already holds .claude/pipeline/ WITH a package_source
#     (already installed — use `package.py upgrade` instead) -> already-installed
#   - a shim path already holds a file without the generated marker -> collision
#
# On success it runs `git subtree add --squash`, then re-execs the freshly
# added copy's package.py to write .claude/pipeline.conf, generate shims,
# add the root CLAUDE.md import line, and commit the wire commit. It never
# pushes and never runs bootstrap.sh — those are the owner's own steps
# (ADR-0092 D3; ADR-0001 D12 hard rules 2-3 stand outside throwaway
# verification repositories).

set -eu

SOURCE=""
TAG=""
INTEGRATION=""
RELEASE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --source) SOURCE="$2"; shift 2 ;;
        --tag) TAG="$2"; shift 2 ;;
        --integration) INTEGRATION="$2"; shift 2 ;;
        --release) RELEASE="$2"; shift 2 ;;
        *) echo "install.sh: unknown argument: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$SOURCE" ] || [ -z "$TAG" ]; then
    echo "usage: install.sh --source <url> --tag vX.Y.Z [--integration <b>] [--release <b>]" >&2
    exit 2
fi

if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    echo "package.py: refused (dirty-tree): working tree has uncommitted changes" >&2
    exit 1
fi

if [ -d ".claude/pipeline" ]; then
    if [ -f ".claude/pipeline.conf" ] && grep -q '^package_source=' .claude/pipeline.conf 2>/dev/null; then
        echo "package.py: refused (already-installed): .claude/pipeline/ already tracks a package_source; use \`package.py upgrade\` instead" >&2
    else
        echo "package.py: refused (home-repository): .claude/pipeline/ already exists here without a package_source (this looks like the home repository)" >&2
    fi
    exit 1
fi

# Collision refusal (ADR-0092 D2): this slice's only shim target.
if [ -f ".claude/skills/grill-me/SKILL.md" ] && ! grep -q 'GENERATED by \.claude/pipeline/tools/package\.py refresh from' ".claude/skills/grill-me/SKILL.md" 2>/dev/null; then
    echo "package.py: refused (collision): .claude/skills/grill-me/SKILL.md exists without the generated marker" >&2
    exit 1
fi

git subtree add --prefix=.claude/pipeline "$SOURCE" "$TAG" --squash \
    -m "chore(pipeline): install $TAG"

INSTALL_ARGS="--source $SOURCE"
if [ -n "$INTEGRATION" ]; then INSTALL_ARGS="$INSTALL_ARGS --integration $INTEGRATION"; fi
if [ -n "$RELEASE" ]; then INSTALL_ARGS="$INSTALL_ARGS --release $RELEASE"; fi

# shellcheck disable=SC2086
python3 .claude/pipeline/tools/package.py install $INSTALL_ARGS
