#!/usr/bin/env python3
"""
tools/gen_rules.py — generate .claude/rules/<scope>.md from ADR frontmatter.

Mirrors the dashboard/readme_gen.py pattern (stdlib-only, no third-party
YAML parser needed — frontmatter is simple key: value syntax).

Rule ID scheme: <SCOPE3>-NNN where SCOPE3 is the first 3 characters of the
scope name uppercased (e.g. scope "capture" → "CAP"), and NNN is a zero-padded
counter within that scope.  Rule IDs are declared in ADR frontmatter
``rule_ids`` lists and are STABLE — never reused, never reordered.

ADR Frontmatter keys (required for inclusion):
  id           — ADR identifier (e.g. "ADR-0006")
  status       — "accepted" | "superseded" (case-insensitive)
  supersedes   — list of ADR IDs this supersedes (may be empty list)
  superseded_by — list of ADR IDs that supersede this (may be empty list)
  scope        — short slug (e.g. "capture", "commits", "pipeline")
  rule_ids     — list of stable rule_ids (e.g. ["CAP-001", "CAP-002"])

ADRs with status "superseded" (or any superseded_by entry) are excluded from
the generated output.  ADRs without frontmatter are skipped gracefully.

Scope→target convention (ADR-0073 D1 + D3; relocated per slice #945):
  GLOBAL scopes are rendered into .claude/generated/_global.md, which
  CLAUDE.md @imports with a single line: @.claude/generated/_global.md
  This keeps CLAUDE.md lean (<200 lines) while ensuring rules are always-loaded.
  .claude/generated/ is NOT an auto-loaded directory (unlike .claude/rules/),
  so the @import is the ONLY load path — no double-load (slice #945).
  AREA scopes are rendered into .claude/rules/<scope>.md with a paths:
  frontmatter key so Claude Code loads them only when editing matching files.

Output:
  GLOBAL scope: .claude/generated/_global.md (@import target, not auto-loaded)
  AREA scope:   .claude/rules/<scope>.md (with paths: frontmatter)

Header (inside generated files): <!-- GENERATED by tools/gen_rules.py — DO NOT EDIT -->

Usage:
  python tools/gen_rules.py          # writes all discovered scopes
  python tools/gen_rules.py --check  # dry-run: exits non-zero if output differs
"""

# NOTE (slice #945): _global.md previously lived in .claude/rules/, which
# Claude Code auto-loads unconditionally for every *.md file lacking a
# paths: key — the SAME file was then ALSO @imported by CLAUDE.md, so it
# loaded twice per session.  It now lives in .claude/generated/ (not an
# auto-loaded directory), so the @import is the sole load path.

import os
import sys
import glob
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Repo root resolution (mirrors readme_gen._resolve_invoking_repo_root)
# ---------------------------------------------------------------------------

def _resolve_repo_root() -> Path:
    """Resolve the repo root from the invoking worktree's cwd."""
    import subprocess
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=5, cwd=os.getcwd(),
        )
        if result.returncode == 0:
            root = Path(result.stdout.strip())
            if root.is_dir():
                return root
    except Exception:
        pass
    # Fallback: script-file parent's parent
    return Path(__file__).resolve().parent.parent


REPO_ROOT = _resolve_repo_root()
DECISIONS_DIR = REPO_ROOT / "decisions"
RULES_DIR = REPO_ROOT / ".claude" / "rules"
# GLOBAL scopes render into .claude/generated/ (NOT .claude/rules/) because
# .claude/rules/*.md files lacking a paths: key are auto-loaded unconditionally
# by Claude Code — placing the @import target there double-loads it (#945).
GENERATED_DIR = REPO_ROOT / ".claude" / "generated"
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"
GLOBAL_RULES_FILE = GENERATED_DIR / "_global.md"
GENERATED_HEADER = (
    "<!-- GENERATED by tools/gen_rules.py — DO NOT EDIT — regenerate to update -->\n"
)
# The @import line that CLAUDE.md uses to load all global rules (ADR-0073 D1).
CLAUDE_MD_GLOBAL_IMPORT = "@.claude/generated/_global.md"

# ---------------------------------------------------------------------------
# Scope→target classification (ADR-0073 D1 + D3 — single source)
# GLOBAL: always-relevant rules rendered into .claude/generated/_global.md,
#         which CLAUDE.md @imports — always loaded, keeps CLAUDE.md lean.
#         .claude/generated/ is NOT auto-loaded, so the @import is the sole
#         load path (slice #945 — previously .claude/rules/ double-loaded it).
# AREA:   context-specific rules rendered into path-scoped .claude/rules/ files.
# A scope is EITHER global OR area — never both (no double-load).
# ---------------------------------------------------------------------------

SCOPE_TARGET: dict[str, str] = {
    # GLOBAL — always-relevant, rendered into CLAUDE.md
    "pipeline":        "global",
    "capture":         "global",
    "commits":         "global",
    "critics":         "global",
    "verification":    "global",
    "regression":      "global",
    "output-contracts": "global",
    "glossary":        "global",
    # AREA — path-scoped, rendered into .claude/rules/<scope>.md
    "hooks":           "area",
    "isolation":       "area",
    "docs":            "area",
    "slicing":         "area",
}

# paths: frontmatter values for each AREA scope.
# These tell Claude Code to load the rules file only when the relevant files
# are being edited — the sole advantage of a separate rules file (ADR-0073 D1).
SCOPE_PATHS: dict[str, str] = {
    "hooks":     ".claude/hooks/**, .claude/settings.json",
    "isolation": ".claude/worktrees/**, tools/worktree-guard.sh",
    "docs":      "decisions/**, **/*.md",
    "slicing":   ".claude/agents/slicer*.md, .claude/skills/*/SKILL.md",
}

# Rule-ID conservation baseline (PRD #937 slice #939 — §2 criterion 7).
# This is the TOTAL number of rule_ids across all active ADR scopes as of the
# scope-migration commit (slice #939, 2026-06-18); bumped by ADR-0076's 6 new
# PIP-* ids (slice #1129), then by ADR-0077's 2 new PIP-* ids (slice #1162),
# then by ADR-0078's 1 new PIP-* id (slice #1172), then by ADR-0079's 1 new
# PIP-* id (slice #1197), then by ADR-0080's 1 new PIP-* id (slice #1217),
# then by ADR-0081's 1 new PIP-* id (slice #1238), then by ADR-0083's 2 new
# VER-* ids (slice #1310).
# --check verifies that the live count equals this value; a mismatch means a
# rule was silently added or removed without updating this constant.
# Note: ADR-0081's supersessions are all per-decision, so no ADR leaves the
# active frontmatter set and no rule_ids are removed — the delta is +1 only.
# ADR-0083's supersession of ADR-0057 D2 is likewise per-decision: ADR-0057
# keeps `superseded_by: []`, so HOK-008/HOK-009 stay in the active set and the
# ADR-0083 delta is +2 (VER-009, VER-010) with nothing removed.
# ADR-0085 (slice #1329) adds 4 new PIP-* ids (PIP-026..PIP-029) and has
# `supersedes: []`, so nothing leaves the active set: the delta is +4.
# ADR-0084 (slice #1402) adds 2 new VER-* ids (VER-011, VER-012); its
# `supersedes: ["ADR-0049 D3"]` is per-decision partial like ADR-0083's
# supersession of ADR-0057 D2 above — ADR-0049 is not edited and keeps
# `superseded_by: []` (immutable), so nothing leaves the active set: the
# delta is +2.
# Issue #1464 (fix, no new ADR): ADR-0013's frontmatter `superseded_by: []`
# was stale — decisions/README.md and ADR-0044 both already document
# ADR-0013 D1-D4 as superseded by ADR-0044 (D5/D6 unaffected), but the
# frontmatter never caught up, so `_is_superseded()` (whole-ADR) kept
# rendering ADR-0013's rules. Populating `superseded_by: ["ADR-0044"]`
# correctly drops ADR-0013's SLI-004 and SLI-005 (the retired N=1-vs-N=3
# degenerate-decomposition machinery ADR-0044 D2 replaced) — no other ADR's
# rule_ids are affected: the delta is -2.
# ADR-0088 (slice #1481) fully supersedes ADR-0078 (`status: "superseded"`,
# `superseded_by: ["ADR-0088"]`), so ADR-0078 leaves the active frontmatter
# set entirely and its sole rule_id, PIP-022, drops: -1. ADR-0088 itself
# declares `rule_ids: []` — its D2 observability-doc obligation is
# (advisory) and D3-D6 extend existing checks rather than minting new
# rule ids — so it adds nothing back: the net delta is -1, measured from
# the baseline on `develop` at the commit this slice branched from (92).
# ADR-0089 (slice #1511) adds 2 new PIP-* ids (PIP-031, PIP-032). Its four
# supersessions (ADR-0070 D1, ADR-0004 D3, ADR-0041 D2, ADR-0045 D3) are all
# per-decision partial, so `superseded_by: []` stays on every one of them and
# no rule_id drops: the delta is +2, measured from the baseline on `develop`
# at the commit this slice branched from (91).
# ADR-0090 (slice #1506) adds 2 new PIP-* ids (PIP-033, PIP-034). Its eight
# supersessions (ADR-0003 D1, ADR-0024 D1/D2, ADR-0063 D1, ADR-0085 D1/D3/D5/
# D6) are all per-decision partial, so `superseded_by: []` stays on every one
# of them and no rule_id drops: the delta is +2, measured from the baseline
# on the integration branch at the commit this slice branched from (93).
# Breakdown: CAP(8) + COM(2) + CRI(5) + DOC(6) + GLO(4) + HOK(9) +
#            ISO(6) + OUT(5) + PIP(32) + REG(3) + SLI(3) + VER(12) = 95
RULE_IDS_BASELINE: int = 95

# ---------------------------------------------------------------------------
# Frontmatter parser (stdlib, no PyYAML)
# ---------------------------------------------------------------------------

def _parse_frontmatter(text: str) -> dict | None:
    """
    Parse YAML frontmatter from the top of an ADR file.

    Returns a dict of key→value if frontmatter is present, else None.
    Only supports the subset of YAML used in ADR frontmatter:
      - scalar strings (quoted or unquoted)
      - empty lists: []
      - inline list items starting with "  - " lines
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None

    # Find the closing ---
    close_idx = None
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            close_idx = i
            break
    if close_idx is None:
        return None

    fm_lines = lines[1:close_idx]
    result: dict = {}
    current_key: str | None = None

    for line in fm_lines:
        # List item continuation
        if line.startswith("  - ") and current_key is not None:
            item = line[4:].strip().strip('"').strip("'")
            if not isinstance(result.get(current_key), list):
                result[current_key] = []
            result[current_key].append(item)
            continue

        # Empty list shorthand: key: []
        m = re.match(r'^(\w+):\s*\[\s*\]\s*$', line)
        if m:
            current_key = m.group(1)
            result[current_key] = []
            continue

        # Scalar: key: value
        m = re.match(r'^(\w+):\s*(.*)', line)
        if m:
            current_key = m.group(1)
            val = m.group(2).strip().strip('"').strip("'")
            result[current_key] = val
            continue

    return result


# ---------------------------------------------------------------------------
# ADR discovery
# ---------------------------------------------------------------------------

def _load_adrs() -> list[dict]:
    """
    Load all ADRs in decisions/ that have frontmatter.

    Returns list of dicts with keys:
      path, id, status, supersedes, superseded_by, scope, rule_ids
    """
    adrs = []
    for adr_path in sorted(DECISIONS_DIR.glob("[0-9]*.md")):
        try:
            text = adr_path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue

        fm = _parse_frontmatter(text)
        if fm is None:
            # No frontmatter — skip gracefully
            continue

        # Normalize required keys
        adr_id = str(fm.get("id", "")).strip()
        status = str(fm.get("status", "")).strip().lower()
        supersedes = fm.get("supersedes", [])
        if isinstance(supersedes, str):
            supersedes = [supersedes] if supersedes else []
        superseded_by = fm.get("superseded_by", [])
        if isinstance(superseded_by, str):
            superseded_by = [superseded_by] if superseded_by else []
        scope = str(fm.get("scope", "")).strip()
        rule_ids = fm.get("rule_ids", [])
        if isinstance(rule_ids, str):
            rule_ids = [rule_ids] if rule_ids else []

        if not adr_id or not scope or not rule_ids:
            # Incomplete frontmatter — skip
            continue

        adrs.append({
            "path": adr_path,
            "id": adr_id,
            "status": status,
            "supersedes": supersedes,
            "superseded_by": superseded_by,
            "scope": scope,
            "rule_ids": rule_ids,
        })

    return adrs


def _is_superseded(adr: dict) -> bool:
    """Return True if this ADR is superseded (should be excluded from digest)."""
    if adr["status"] == "superseded":
        return True
    if adr.get("superseded_by"):
        return True
    return False


# ---------------------------------------------------------------------------
# Rule statement extraction
# ---------------------------------------------------------------------------

# Map rule_id prefix to a one-line human-readable statement.
# These statements are derived from the core decisions in each ADR.
# Format: rule_id → one-line statement.
_RULE_STATEMENTS: dict[str, str] = {
    # ADR-0006: forward-work backlog queue
    "CAP-001": (
        "Agents write `captured`-labeled issues for every deferred or "
        "forward-looking item they identify."
    ),
    "CAP-002": (
        "Session continuity is achieved via live-state reconstruction "
        "(git log + open issues + PRs) — no formal handoff document."
    ),
    # ADR-0008: two-tier captured→backlog + backlog-critic
    "CAP-003": (
        "Captured items are auto-evaluated by `backlog-critic`; APPROVE "
        "promotes to `backlog`, BLOCK leaves in `captured` for human review."
    ),
    "CAP-004": (
        "Backlog-critic evaluates four criteria: Actionable, Scoped, "
        "Not-duplicate, Clear — defaulting to BLOCK when uncertain."
    ),
    # ADR-0024: root-cause discipline
    "CAP-005": (
        "Every workflow mistake MUST produce a `captured`-labeled root-cause "
        "capture (rule #13): symptom + root cause + proposed fix."
    ),
    "CAP-006": (
        "Root-cause captures use the 3-section shape: Symptom observed / "
        "Root cause analyzed / Proposed workflow change."
    ),
    # ADR-0063: capture-shape contract
    "CAP-007": (
        "Root-cause captures carry a `root-cause` label alongside `captured` "
        "to make the class mechanically queryable."
    ),
    "CAP-008": (
        "Root-cause section headings are regex-detectable: `**Symptom:**` / "
        "`**Root cause:**` / `**Proposed:**`; evidence is preserved verbatim "
        "before diagnosing (STOP → PRESERVE → DIAGNOSE → FIX → GUARD → RESUME)."
    ),
    # ADR-0002: autonomous merge policy (D9-revised)
    "PIP-001": (
        "Reviewer's APPROVE verdict triggers auto-merge (`gh pr merge --squash`); "
        "BLOCK sends the PR back to the implementer; after N=3 rounds, escalate to human."
    ),
    # ADR-0003: autonomous pipeline + critics
    "PIP-002": (
        "The unit-of-delivery hierarchy is exactly three tiers: PRD (prd-labeled issue) "
        "→ Slice (slice-labeled sub-issue) → PR (closes one slice); as amended by "
        "ADR-0090 D4: a release-mode lane PR closes one or more `bug` issues and no slice."
    ),
    "PIP-003": (
        "The pipeline has five stages: grill-me → to-prd+prd-critic → slicer+slicer-critic "
        "→ implementer+reviewer → qa-plan; every generation stage is paired with an "
        "adversarial critic."
    ),
    "PIP-004": (
        "The human enters the pipeline at exactly two points: `grill-me` (defines what to "
        "build) and `qa-plan` (acceptance test); everything in between is fully autonomous."
    ),
    "PIP-005": (
        "Human-facing stages use skills (orchestrator-owned procedures); autonomous stages "
        "use subagents (isolated-context + task-handed + result-returning)."
    ),
    # ADR-0010: implementer subagent + /ship auto-invoke
    "PIP-006": (
        "A single `implementer` subagent handles all slice types (feat/fix/docs/refactor/"
        "test) uniformly — no specialized variants until data justifies splitting."
    ),
    "PIP-007": (
        "`/ship` auto-invokes the implementer on each posted slice, closing the residual "
        "human-trigger gap and making ADR-0003 D4's no-human-gates property enforceable "
        "end-to-end."
    ),
    "PIP-008": (
        "Orchestrator reads each slice's `Depends on` field, builds the DAG, and runs "
        "independent slices in parallel; sync points are at dependency boundaries."
    ),
    "PIP-009": (
        "On irrecoverable failure (round-3 BLOCK; ambiguous AC; INVALID_INPUT), the "
        "failed slice gets `needs-human`; in-flight parallel slices finish normally; "
        "slices depending on the failed slice stay blocked."
    ),
    "PIP-010": (
        "Implementer's authorized tools: Read, Edit, Write, Bash, Glob, Grep. "
        "Explicitly excluded: Agent (no recursive subagent invocation — reviewer is "
        "invoked by /ship orchestrator, not by the implementer)."
    ),
    # ADR-0046: codebase-critic + parsimony reframe
    "PIP-011": (
        "The gate on adding a critic is a parsimony principle (minimize critics; each "
        "earns its place against a distinct concern no existing critic absorbs) — not a "
        "numeric count cap."
    ),
    "PIP-012": (
        "`codebase-critic` provides per-PRD macro review covering: (1) semantic doc "
        "currency, (2) architectural drift, (3) refactoring opportunities; BLOCK for "
        "PRD-introduced drift, RECOMMEND for improvements."
    ),
    "PIP-013": (
        "`codebase-critic` fires once per PRD at the last open slice, before that "
        "slice's reviewer pass, judging the cumulative PRD diff; reviewer remains "
        "the sole merge gate."
    ),
    # ADR-0076: guarded-verb pipeline engine
    "PIP-014": (
        "The complete verb set (`tools/pipe/{dispatch,pr-open,pr-merge,qa-verify,"
        "prd-close,record-green}` + `tools/promote.sh`) is the sole "
        "sanctioned path for mechanical pipeline transitions: precondition checks "
        "→ side effect → atomic v3 span; a refused transition exits non-zero and "
        "never half-succeeds (ADR-0076 D1, as amended by ADR-0080 D2 — "
        "`batch-plan` retired)."
    ),
    "PIP-015": (
        "`tools/trace.py` accepts only the closed kind set {pr_opened, pr_merged, "
        "qa_verified, develop_green, promotion, dispatch, dispatch_end, verdict}; "
        "an unknown kind is a hard error (non-zero, nothing "
        "written) (ADR-0076 D2, as amended by ADR-0080 D2 — `batch_planned` "
        "retired)."
    ),
    "PIP-016": (
        "`tools/pipe/pr-merge` refuses to merge a slice PR lacking a reviewer "
        "comment containing `VERDICT: APPROVE` and emits a `verdict` span derived "
        "from the comment it verified; `develop` gains server-side branch "
        "protection requiring the `ci` status context (ADR-0076 D3)."
    ),
    "PIP-017": (
        "The PreToolUse(Bash) validation hook DENIES exactly three incident-backed "
        "raw forms with a working sanctioned alternative (raw `gh pr merge`, "
        "subagent-context `tools/promote.sh`, refspec-form pushes to main) and "
        "advisory-nudges `gh issue create --label slice|prd` rather than denying "
        "it (no sanctioned posting verb exists yet) (ADR-0076 D4)."
    ),
    "PIP-018": (
        "Each verb's landing PR deletes the SKILL.md prose block it mechanizes in "
        "the same PR — reviewer-checkable via a named grep count=0 while the verb "
        "call site remains (ADR-0076 D5)."
    ),
    "PIP-019": (
        "Sequencing between verbs stays LLM judgment this phase; a sequencing-as-"
        "code executor is commissioned only if the recorded evidence trigger "
        "fires (nonzero RECORD-VS-GH emission-gap rate after 2+ PRDs, or one new "
        "bypass incident) (ADR-0076 D6)."
    ),
    # ADR-0077: ceremony-overhead reduction (operator-directed)
    "PIP-020": (
        "The R-LOC cap rises from 300 to 600 LoC of runtime-artifact diff "
        "(reviewer.md remains the sole canonical definition site); the slicer "
        "targets 3-5 slices per PRD for equivalent scope, down from the ~6-9 a "
        "300-LoC cap implied (ADR-0077 D1)."
    ),
    "PIP-021": (
        "The reviewer dispatches immediately at PR-open, concurrent with the "
        "PR's `ci` run, instead of waiting for a terminal CI state; before any "
        "merge it polls `gh pr checks` itself and, on a CHECK-3 format-class "
        "failure, flips its own verdict to BLOCK with the same corrective "
        "message as before, reusing its own round-cap rather than a separate "
        "orchestrator-tracked counter (ADR-0077 D2)."
    ),
    # ADR-0078: run-board as the dashboard's landing view
    "PIP-022": (
        "`/api/runboard` serves now/recent strictly from recorded v3 "
        "spans (never inferred, backfilled, or reconstructed), rendered "
        "as the dashboard's only tab; the "
        "production check fails outright if any rendered row cannot be "
        "traced to a canonical-ledger span, the board renders normally "
        "while the ledger is unreadable, or the ledger holds no "
        "dispatch span in the verification window "
        "(ADR-0078 D1, as amended by ADR-0080 D1 — the "
        "architecture-view-one-click-away clause retired; the dashboard is "
        "reduced to the run-board plus a thin health strip)."
    ),
    # ADR-0079: recorded-CI trust post-merge + sha-attributed evidence + hook diet
    "PIP-023": (
        "Post-merge green evidence is the recorded GitHub `ci` conclusion for "
        "the exact merged/certified sha — deriving that sha internally from a "
        "local ref (rather than receiving it as a parameter) is forbidden on "
        "evidence paths, and a mismatch between the certified sha and the "
        "evidence sha refuses rather than proceeds (ADR-0079 D1/D2); the "
        "separate always-run `bash tools/ci-checks.sh` SKILL-mandated re-run "
        "is deleted at all three sites since record-green's own recorded-CI-"
        "trust logic already performs the equivalent verification (ADR-0079 "
        "D1b)."
    ),
    # ADR-0080: frontend reduced to the run-board; batch-plan verb retired
    "PIP-024": (
        "`tools/pipe/batch-plan` is retired and `batch_planned` leaves "
        "`tools/trace.py`'s closed kind enum (zero recorded spans, "
        "verified); the verb returns only via a new ADR gated on two "
        "`captured` issues from distinct PRDs each documenting a concrete "
        "mis-dispatch or planning failure caused by absent recorded batch "
        "state (ADR-0080 D2; its board-panel clause lapsed when ADR-0088 "
        "retired the board)."
    ),
    # ADR-0081: post-audit dead-weight retirements (4 mechanisms, duties rehomed)
    "PIP-025": (
        "Four audit-flagged mechanisms are retired with every load-bearing duty "
        "explicitly rehomed: the dedicated QA-residual clearing skill (the "
        "`needs-human-check` queue, PROVISIONAL semantics, and machine-PASS "
        "auto-close all stand — the operator clears residuals via the "
        "out-of-repo decide-flow or `gh issue list`), the `/glossary` skill and "
        "its critic (glossary content and the ~35 soft cap stand — additions "
        "ride normal reviewer-gated PRs and DOCS-9 checks the cap; critic "
        "roster 7 → 6), the golden-set critic-eval harness (the `tests/` suite, "
        "R-PROVE, and the flaky quarantine stand), and the `/build` conductor "
        "(its three non-duplicated steps fold into `/ship`, the single "
        "lifecycle orchestrator); each returns only via a new ADR that "
        "re-argues its case (ADR-0081 D1/D2/D3/D4)."
    ),
    # ADR-0085: /ship queue-drain entry mode (whole-queue autonomous runs)
    "PIP-026": (
        "`/ship`'s queue-drain entry mode is the sole whole-queue drain path: "
        "the queue assembles from open `prd`/`slice`/`backlog`/`captured` "
        "issues plus open non-draft PRs; captured items enter execution only "
        "via the captured→backlog autopilot (ADR-0008 D2, the sweep ADR-0008 "
        "D3 anticipates) and backlog items ride the standard PRD→slicer flow "
        "(rule #16); triage uses the reasonable-engineer litmus with "
        "label-and-continue escalation onto `needs-human-check` — never "
        "`needs-human`, which stays the round-3/I5 strict-stop surface that "
        "gates ADR-0070 D2 promotion — and the run never blocks on a human "
        "answer; hard invariants (no agent-created PROMOTE_OK per ADR-0070 "
        "D4, round-3 strict-stop, destructive-op confirmation, worktree "
        "isolation, slicer-only slice creation) are absolute and not "
        "triage-overridable (ADR-0085 D1/D2); as amended by ADR-0090 D2: a "
        "release run's work set is its version's bugs and admitted features; "
        "bugs without a design fork ride lane PRs, and admitted features the "
        "PRD → slicer flow."
    ),
    "PIP-027": (
        "Drain parallelism lifts the slice model to queue level: file-overlap "
        "lanes, independent lanes parallel in isolated worktrees, at most 3 "
        "items concurrently in flight (enforced by DRAIN-LEDGER), unknown "
        "overlap serializes, merges serialize through the PR gate per "
        "ADR-0062 D2 (ADR-0085 D3); as amended by ADR-0090 D3: a release run "
        "allows 15 lanes in flight."
    ),
    "PIP-028": (
        "Every drain run appends to `.claude/logs/drain/<run-id>.jsonl` at the "
        "git-common-dir root with the closed kind set {run_start, triaged, "
        "item_start, item_done, escalated, fix_queued, fixed_in_run, parked, "
        "resumed, run_end} and lane assignment as a field on `triaged`; "
        "trace-v3's enum is untouched; a park writes a `parked` record naming "
        "remaining items in resume order, including every still-unlanded "
        "`fix_queued`; the DRAIN-LEDGER health row enforces schema, kinds, "
        "recorded-escalation completeness, triage-precedence, the concurrency "
        "bound, and fix-queued parity — evaluated from the ledger alone, never "
        "from live GitHub state (ADR-0085 D4/D6)."
    ),
    "PIP-029": (
        "Trivial-lane discoveries land inside the drain run as their own "
        "`hotfix/*` PRs recorded `fixed_in_run`; a drain run may not reach its "
        "terminal record with a `fix_queued` item that lacks a `fixed_in_run`, "
        "a `captured_ref`, or (on a park) a place in the remaining-items list; "
        "I3's definition, rule #13 root-cause captures, and the ADR-0067 "
        "regression rider are unchanged (ADR-0085 D5)."
    ),
    # ADR-0089: per-repo pipeline identity — configured branch roles (D1/D3)
    # + repo-agnostic history anchors (D4)
    "PIP-031": (
        "Pipeline executables (`tools/`, `dashboard/`, `.claude/hooks/`, "
        "`.githooks/`, `bootstrap.sh`) and agent/skill prompt commands name "
        "the integration or release branch only through "
        "`tools/pipeline_config.py`, which reads the tracked "
        "`.claude/pipeline.conf` (defaults `develop`/`main`). Agents branch "
        "from, diff against, verify on and open PRs to the integration "
        "branch. CI CHECK 29 fails on a literal branch token in that "
        "defined subject set (ADR-0089 D1/D3)."
    ),
    "PIP-032": (
        "A health-check grandfather anchor is an ISO-8601 UTC instant in "
        "`dashboard/_constants.py` `GRANDFATHER_UNTIL`, compared against "
        "merge time through `grandfathered()`. It is never a PR/issue "
        "number or commit sha of this repo. CI CHECK 29 fails on a numeric "
        "or sha-valued anchor constant (ADR-0089 D4)."
    ),
    # ADR-0090: release mode for /ship (freeze a version, drain bugs through
    # script-briefed file lanes)
    "PIP-033": (
        "Every issue carries exactly one class label at creation: `bug` "
        "(anything that breaks the system's own promise, docs, rules, ADRs "
        "and doc drift included) or `feature`; residuals (`needs-human-check` "
        "issues without `bug`: QA residuals and pure policy questions) are "
        "exempt and never admitted to a milestone. `/ship release <version>` "
        "is a queue-drain sub-form: `tools/release.py freeze <V> --next <W> "
        "--features <list>` refuses on an unclassified issue, admits every "
        "open bug and the owner's listed features with their slices to "
        "`<V>`, and moves every other feature to `<W>`; bugs without a "
        "design fork ride lane PRs, not the PRD pipeline, and admitted "
        "features ride the PRD → slicer flow. A version is done when "
        "`RELEASE-GATE` PASSes (zero open non-residual issues in its "
        "milestone, zero open non-residual bugs in none, zero unclassified "
        "open issues), so a bug escalated to the owner holds it; only the "
        "owner promotes and tags (ADR-0090 D1/D2)."
    ),
    "PIP-034": (
        "Release-mode bugs are fixed in lane PRs: one fresh Sonnet builder "
        "per disjoint file lane, dispatched only through `tools/pipe/"
        "dispatch --lane`, whose packet (evidence, excerpts from "
        "`origin/develop` at dispatch, check) is the builder's brief; "
        "branch `fix/<n>-lane-<slug>`, label `lane`, closing only `bug` "
        "issues and never slice or PRD issues; R-LOC 600 applies. "
        "`tools/pipe/pr-merge` merges a lane PR only on an APPROVE whose "
        "`MODEL:` is not Sonnet or Haiku, with every commit inside a "
        "dispatch window of its lane, then closes its bugs. DRAIN-LEDGER "
        "caps a release run at 15 lanes in flight, and `tools/release.py "
        "verify` checks each bug after merge (ADR-0090 D3/D4)."
    ),
    # -----------------------------------------------------------------------
    # hooks scope (ADR-0015, ADR-0023, ADR-0033, ADR-0057)
    # -----------------------------------------------------------------------
    # ADR-0015: hooks adoption — D1 (config location) + D2 (scope policy)
    "HOK-001": (
        "Project-wide Claude Code hooks are configured in `.claude/settings.json` "
        "under the `hooks` section; per-developer overrides via `.claude/settings.local.json` "
        "are not used by default (ADR-0015 D1)."
    ),
    "HOK-002": (
        "Hooks are limited to three permitted categories: logging (write to local files), "
        "validation (exit-code block/ask), and notification (stderr message). "
        "Hooks MUST NOT auto-invoke Claude Code skills or subagents (ADR-0015 D2, source=CLAUDE.md #12)."
    ),
    # ADR-0023: validation + notification hooks — D3 (pre-tool-edit) + D4 (bash-block) + D5 (prompt-nudge)
    "HOK-003": (
        "A PreToolUse(Edit|MultiEdit|Write) hook mechanically escalates rule #10 "
        "(main-agent meta-output discipline): it emits `permissionDecision: \"ask\"` "
        "when the main agent attempts to write a tracked file, unless the write is in a "
        "subagent context (ADR-0023 D3)."
    ),
    "HOK-004": (
        "A PreToolUse(Bash) hook blocks `git push origin main` (any flavor) with "
        "`permissionDecision: \"deny\"`, enforcing rule #4 at the session level (ADR-0023 D4)."
    ),
    "HOK-005": (
        "A SessionStart hook injects live workflow state (branch, divergence vs origin/main, "
        "open slices, open PRs, open captured items) into every new session's context, "
        "mitigating the stale-worktree false-alarm pattern (ADR-0023 D2)."
    ),
    # ADR-0033: tooling-spawn — D1 (fourth category) + D2 (skill/subagent exclusion preserved)
    "HOK-006": (
        "A fourth hook category is permitted: **tooling-spawn** — hooks may spawn "
        "project-local tooling processes that meet ALL FOUR criteria: no LLM API calls, "
        "localhost-only binding, project-scoped script, idempotent spawn check (ADR-0033 D1)."
    ),
    "HOK-007": (
        "The tooling-spawn carveout does NOT authorize hook scripts to invoke "
        "`.claude/skills/` skills or `.claude/agents/` subagents. ADR-0015 D2's core "
        "intent — preventing hooks from auto-billing the user via LLM calls — is "
        "preserved unchanged (ADR-0033 D2)."
    ),
    # ADR-0057: fail-loud + context-injection — D1 (fail-loud) + D4 (fifth category)
    "HOK-008": (
        "Every hook script MUST emit an attempt beacon BEFORE any parsing or branching; "
        "on any internal error it MUST emit an ERROR beacon to `hook-fires.jsonl` rather "
        "than exiting silently; every terminal path MUST append exactly one terminal "
        "beacon before exiting — a deliberate policy decision (DENY/ASK/WARN) is a "
        "completion, so it exits `status:\"ok\"` and records the decision in the additive "
        "`outcome` field, never in `status`; `status` is drawn from the closed set "
        "{attempt, ok, ERROR} and nothing else; payloads are parsed in full via python3 — "
        "never truncated with `head -c` (ADR-0057 D1, fail-loud contract, as amended by "
        "ADR-0083 D1/D2)."
    ),
    "HOK-009": (
        "A fifth hook category is permitted: **context injection** — a SessionStart hook "
        "MAY inject deterministic, read-only command output into session context. The hard "
        "line is unchanged: hooks NEVER auto-invoke skills or subagents (ADR-0057 D4, "
        "source=CLAUDE.md #12)."
    ),
    # -----------------------------------------------------------------------
    # slicing scope (ADR-0005, ADR-0013)
    # -----------------------------------------------------------------------
    # ADR-0005: output-shape + slicing methodology — D2 (slicing methodology) + D3 (cascade-doc)
    "SLI-001": (
        "Slice 1 of every multi-slice PRD MUST be a walking-skeleton — it cuts through "
        "every pipeline layer end-to-end (hamburger method), even if crudely; building one "
        "layer completely before another is explicitly rejected (ADR-0005 D2, source=CLAUDE.md #2)."
    ),
    "SLI-002": (
        "When a slice approaches the LoC cap, the slicer uses SPIDR split-fallback hints "
        "(Spike / Path / Interface / Data / Rules); S, I, and R are the dominant splits for "
        "this agent-workflow domain (ADR-0005 D2)."
    ),
    "SLI-003": (
        "For each candidate decomposition, the slicer MUST identify cascade-docs — files "
        "that should update to reflect the new feature even when not strictly required by "
        "acceptance criteria — and add a slice or merge coverage for each; the slicer-critic "
        "enforces this check (ADR-0005 D3, source=CLAUDE.md #16)."
    ),
    # ADR-0013: N=1 degenerate carveout — D1 (slicer self-restraint) + D2 (critic acceptance)
    "SLI-004": (
        "When all N candidate decompositions would produce bit-identical post-merge end-state "
        "(same files, same LoC, same content — modulo commit ordering), the slicer declares "
        "N=1 with explicit rationale instead of fabricating cosmetic variation; N=3 remains "
        "the default for genuinely-open-shape PRDs (ADR-0013 D1)."
    ),
    "SLI-005": (
        "The slicer-critic accepts N=1 with explicit rationale as a legal input; it verifies "
        "the rationale answers: which PRD section locks the shape, which variation axis was "
        "rejected, and whether N=3 would have produced genuinely-different alternatives "
        "(ADR-0013 D2/D3)."
    ),
    # -----------------------------------------------------------------------
    # verification scope (ADR-0037, ADR-0040, ADR-0050, ADR-0083)
    # -----------------------------------------------------------------------
    # ADR-0037: production-verify gate — D1 (mandatory gate) + D2 (auto-routing) + D4 (PRD declares)
    "VER-001": (
        "After all slices of a feature merge, a mandatory, blocking production-verification "
        "gate runs before the feature is 'done'; PASS → feature done; FAIL → gate BLOCKS; "
        "per-feature granularity (not per-slice) (ADR-0037 D1, source=CLAUDE.md #15)."
    ),
    "VER-002": (
        "`qa-tester` in production-verify mode auto-routes by change type: "
        "browser-reachable UI → browser route; hooks/settings → synthetic-payload "
        "fire + log assertion; skills/tools → command run + output "
        "assertion; docs/ADRs → static grep (ADR-0037 D2, as amended by ADR-0088 D5)."
    ),
    "VER-003": (
        "Every PRD §2 must include a 'Production check:' line stating what to exercise and "
        "the expected result; `prd-critic` BLOCKs a PRD whose production-check line is "
        "missing or non-actionable (ADR-0037 D4)."
    ),
    # ADR-0040: QA residual model — D1 (residual model) + D2 (non-blocking) + D5 (fidelity)
    "VER-004": (
        "The machine attempts every PRD §2 criterion; a criterion it cannot faithfully "
        "verify returns PROVISIONAL and becomes a human residual posted as a "
        "`needs-human-check` issue — the residual is discovered empirically, not predicted "
        "at plan time (ADR-0040 D1)."
    ),
    "VER-005": (
        "The human residual does NOT block PRD closure; the PRD auto-closes on machine "
        "PRODUCTION_VERIFY: PASS alone; a machine-confident FAIL still blocks per ADR-0037 "
        "D5 loop; the operator clears residuals on their own cadence via the "
        "out-of-repo decide-flow or `gh issue list --label needs-human-check` — the "
        "dedicated clearing skill is retired (as amended by ADR-0081), the queue "
        "and its semantics stand (ADR-0040 D2)."
    ),
    "VER-006": (
        "`qa-tester` browser route MUST drive real interaction — `page.click()`, "
        "`page.fill()`, `page.goto()` — and assert on what a human sees; `page.evaluate()` "
        "is a last-resort disambiguator only; eval-only proof → PROVISIONAL, not PASS "
        "(ADR-0040 D5)."
    ),
    # ADR-0050: headless Playwright driver — D1 (driver choice) + D2 (tool boundary)
    "VER-007": (
        "Headless Playwright/Chrome (`headless=True`, `channel='chrome'`) is the qa-tester "
        "browser driver for ui-mode and the production-verify browser route; it replaces "
        "Claude_Preview MCP, eliminating the OS-visibility timeout by rendering offscreen "
        "(ADR-0050 D1)."
    ),
    "VER-008": (
        "The qa-tester browser route is driven entirely via `Bash` (write a Python script to "
        "a tmp path via heredoc, execute it, read results); all `mcp__Claude_Preview__*` "
        "calls are dropped; no tracked files are written by the qa-tester (ADR-0050 D2)."
    ),
    # ADR-0083: honest substrate — D3 (check authority) + D5 (guard advisory) + D4 (proof tokens).
    # VER-009 fuses D3 and D5; the `(advisory)` marker is scoped to the D5 half only, because
    # D3's half is mechanized (regression test + reviewer rubric) while judging an arbitrary
    # guard's advisory text against every state consistent with its observation is not.
    "VER-009": (
        "A check may only FAIL a subject on an invariant that subject owes — an accepted ADR "
        "decision, a generated rule id, or a documented interface contract; if the invariant "
        "is not owed the check is wrong, not the subject, and a check's subject set is "
        "defined rather than assumed. **(advisory)** When a guard blocks or warns, its "
        "message states the observation and the states consistent with it, never asserting a "
        "single cause it cannot distinguish (ADR-0083 D3/D5)."
    ),
    "VER-010": (
        "A proof token MUST match a shape the evidence itself produces — a beacon record, a "
        "verification transcript — and MUST NOT match the ordinary prose used to refer to "
        "that evidence (a filename, a log path, a route name, a check id); a PR's route "
        "union is conjunctive, satisfied only when EVERY class in the union has a matching "
        "token; and a check reporting a miss names the route class that lacked a token "
        "(ADR-0083 D4)."
    ),
    # ADR-0084: public-repo portability scrub — D1 (CHECK 25) + D2 (CHECK 26).
    "VER-011": (
        "CI CHECK 25 (PORTABILITY-SCRUB) scans every tracked file for Class A (an OS-account "
        "segment inside a `Users` path) and Class B (a local clone root, drive-letter or "
        "MSYS/Git-Bash mount-form spelling) machine-local path detail, excluding `qa-proof/**`, "
        "`decisions/**`, and `tools/portability-allowlist.txt` itself; hazard-documenting prose "
        "is exempted only via that allowlist, anchored by path plus a literal substring of the "
        "exempted line, never a line number or a whole-file exemption (ADR-0084 D1)."
    ),
    "VER-012": (
        "CI CHECK 26 (QA-PROOF-SHAPE) requires every tracked file under `qa-proof/` to match "
        "`qa-proof/<prd-num>/**`, where `<prd-num>` is a bare numeric segment, except a fixed, "
        "ADR-only-growable grandfather list of nine pre-existing non-conforming files named by "
        "path (ADR-0084 D2)."
    ),
    # -----------------------------------------------------------------------
    # commits scope (ADR-0001)
    # -----------------------------------------------------------------------
    # ADR-0001: foundational design — D12 establishes Conventional Commits + never-push-main
    "COM-001": (
        "Every commit message follows `<type>(<optional scope>): <subject>` "
        "(Conventional Commits); subject is lowercase; subject line is capped at ≤72 chars; "
        "types: feat/fix/docs/chore/refactor/test/perf/style/build/ci "
        "(ADR-0001 D12, source=CLAUDE.md #5)."
    ),
    "COM-002": (
        "Every agent-authored commit MUST carry a `Co-Authored-By: Claude …` trailer; "
        "`Closes #<slice-issue>` belongs in the PR body, NOT the commit subject; "
        "the git log is the changelog — no separate CHANGELOG file "
        "(ADR-0001 D12, source=CLAUDE.md #5/#6)."
    ),
    # -----------------------------------------------------------------------
    # critics scope (ADR-0048, ADR-0054)
    # -----------------------------------------------------------------------
    # ADR-0048: critic-loop r3 policy — D1 (strict-stop) + D2 (complete-class revision)
    "CRI-001": (
        "Round-3 BLOCK from any critic is strict-stop: the pipeline escalates via the I5 "
        "surface (`needs-human` label + parent-context comment) and stops regardless of the "
        "residual's apparent magnitude — no fix-and-ship exception exists (ADR-0048 D1)."
    ),
    "CRI-002": (
        "When revising in response to a critic BLOCK, sweep the ENTIRE flagged defect class "
        "(every instance of the cited pattern — every `ADR-NNNN D<n>` cite, every over-cap "
        "commit, etc.), not only the single named instance; this is CLAUDE.md rule #19 "
        "(ADR-0048 D2)."
    ),
    # ADR-0054: critic output contracts — D1 (provenance) + D2 (CRITIC trailer) + D3 (fixture discipline)
    "CRI-003": (
        "Every critic verdict MUST be accompanied by an output contract — a fenced field-schema "
        "block (`VERDICT`/`REASON`/`ROUND` + optionals) that the orchestrator can parse "
        "programmatically; free-text BLOCKs without a trailer are non-conforming (ADR-0054 D1/D2)."
    ),
    "CRI-004": (
        "Fixture/synthetic data NEVER enters production data stores (`.claude/logs/*`); "
        "fixtures live in `dashboard/fixtures/` and load only behind an explicit flag; "
        "any verification whose evidence derives from fixture-tagged data is INVALID — "
        "this is CLAUDE.md rule #21 (ADR-0054 D3)."
    ),
    "CRI-005": (
        "Every 'done/verified' claim in a wrap-up MUST carry a route-appropriate proof "
        "artifact with data source (real session/PRD/PR id + timestamp) and environment "
        "freshness; a claim without a checkable artifact is NOT a valid 'done' — "
        "this is CLAUDE.md rule #20 (ADR-0054 D4)."
    ),
    # -----------------------------------------------------------------------
    # isolation scope (ADR-0036, ADR-0058)
    # -----------------------------------------------------------------------
    # ADR-0036: worktree isolation all dispatches — D1 (all dispatches) + D2 (reviewer too) + D3 (invariant)
    "ISO-001": (
        "Every git-mutating subagent dispatch — implementer or reviewer, regardless of batch "
        "size — MUST pass `isolation: 'worktree'`; there is no batch-size-1 carve-out "
        "(ADR-0036 D1, source=CLAUDE.md I4a)."
    ),
    "ISO-002": (
        "Reviewer dispatch is isolated via the same `isolation: 'worktree'` mechanism as the "
        "implementer; the same state-pollution risk applies to any subagent that performs git "
        "branch/merge operations (ADR-0036 D2)."
    ),
    "ISO-003": (
        "Dispatched subagents MUST NOT mutate the orchestrator's session worktree or the root "
        "repo; the harness-assigned worktree is the subagent's exclusive write domain "
        "(ADR-0036 D3)."
    ),
    # ADR-0058: isolation as asserted interface — D1 (missing worktreePath) + D2 (step-0 assert) + D3 (guard semantics)
    "ISO-004": (
        "A dispatch result missing `worktreePath` is a dispatch failure — the orchestrator "
        "MUST re-dispatch rather than proceed with a shared-tree agent (ADR-0058 D1)."
    ),
    "ISO-005": (
        "Every dispatched agent MUST assert isolation in Step 0: verify "
        "`git rev-parse --show-toplevel` differs from the orchestrator's repo root; if they "
        "match, return `RESULT: BLOCKED — isolation assertion failed` without any write "
        "(ADR-0058 D2)."
    ),
    "ISO-006": (
        "Post-dispatch guard is ff-only and loud: `branch-restore` fails non-zero on diverged "
        "branches (no silent force-reset); `prune` reclaims clean aged worktrees with no open "
        "PR; all subcommands exit non-zero on unrepaired violations (ADR-0058 D3)."
    ),
    # -----------------------------------------------------------------------
    # docs scope (ADR-0034, ADR-0043, ADR-0045)
    # -----------------------------------------------------------------------
    # ADR-0034: generated-docs currency — D4 (generated README) + D5 (R-DOCS-CURRENT)
    "DOC-001": (
        "`README.md` is a build artifact: `python3 dashboard/readme_gen.py` reads "
        "`README.template.md` + filesystem, writes `README.md`; the file MUST NOT be "
        "hand-edited — always regenerate (ADR-0034 D4; generator entrypoint relocated "
        "by ADR-0088 D3)."
    ),
    "DOC-002": (
        "The reviewer enforces `R-DOCS-CURRENT`: any PR that changes a template placeholder "
        "source without regenerating README.md is BLOCKed; this is the unbypassable currency "
        "gate for generated documentation (ADR-0034 D5)."
    ),
    # ADR-0043: CLAUDE.md restructure — D1 (four sections; rule numbers stable) + D4 (numbered rules)
    "DOC-003": (
        "CLAUDE.md is organized into four sections; rule numbers (#1–#N) are stable anchors — "
        "never renumbered, never deleted (only retired with a note); the numbers are the "
        "canonical cross-reference handles (ADR-0043 D1)."
    ),
    "DOC-004": (
        "Adding a new numbered cross-cutting rule requires promoting it to CLAUDE.md §1; "
        "rule numbers are assigned sequentially from the highest existing anchor "
        "(ADR-0043 D4)."
    ),
    # ADR-0045: ADR-citation discipline — D1 (rule #18) + D2 (decisions/README.md index)
    "DOC-005": (
        "Before citing `ADR-NNNN D<n>` in any drafted ADR/PRD/doc, open the cited ADR and "
        "read the actual `### D<n>` heading — the citation's characterization MUST match that "
        "heading; this is CLAUDE.md rule #18 (ADR-0045 D1)."
    ),
    "DOC-006": (
        "`decisions/README.md` is the canonical decision index; consult it to find the right "
        "ADR file before citing; the adr-critic runs an explicit per-cite citation-ledger "
        "pre-step to verify every D-ID (ADR-0045 D2/D3)."
    ),
    # -----------------------------------------------------------------------
    # output-contracts scope (ADR-0059, ADR-0066)
    # -----------------------------------------------------------------------
    # ADR-0059: output-contract schema v2 — D1 (CRITIC:) + D2 (DIDNT_TOUCH/CONCERNS) + D3 (CONFUSION)
    "OUT-001": (
        "The CRITIC trailer gains a `CRITIC:` field identifying the critic subagent by name; "
        "the orchestrator uses this for provenance tracking and dispatch-trail recording "
        "(ADR-0059 D1)."
    ),
    "OUT-002": (
        "The GENERATOR trailer gains `DIDNT_TOUCH:` (scope-discipline evidence: files "
        "deliberately left alone) and `CONCERNS:` (self-disclosed risk entry points — doubts, "
        "not success claims) fields; both are required keys (ADR-0059 D2)."
    ),
    "OUT-003": (
        "A third GENERATOR RESULT enum is defined: `CONFUSION` — returned when the agent "
        "encounters contradictory instructions or an impossible acceptance criterion; the agent "
        "MUST STOP and name the conflict with 2–3 resolution options rather than guessing "
        "(ADR-0059 D3)."
    ),
    # ADR-0066: upstream spec contract — D1 (EARS criteria) + D2 (coverage traceability)
    "OUT-004": (
        "PRD §2 acceptance criteria MUST lead with an EARS-shaped trigger: "
        "'WHEN <trigger>, the system SHALL <observable behavior>'; criteria without a trigger "
        "carry `Verifiable:` escape-hatch prose; `prd-critic` enforces PC-EARS (ADR-0066 D1)."
    ),
    "OUT-005": (
        "Each PRD §2 criterion maps to exactly one slice via a traceability tag; the "
        "`slicer-critic` enforces SC-COVERAGE — no criterion may be untraced to a slice; "
        "amendments to criteria are append-only (ADR-0066 D2/D3)."
    ),
    # -----------------------------------------------------------------------
    # regression scope (ADR-0067)
    # -----------------------------------------------------------------------
    # ADR-0067: regression memory — D1 (tests/ in CI) + D2 (R-PROVE test-before-fix) + D3 (rule #13 rider)
    "REG-001": (
        "The `tests/` suite is wired into CI: `tools/ci-checks.sh` runs `pytest tests/` as a "
        "required check; a red test suite blocks the PR merge gate (ADR-0067 D1)."
    ),
    "REG-002": (
        "R-PROVE: on fix-type slice PRs the regression test's commit MUST precede the fix "
        "commit in branch history (ADR-0067 D2); separately, rule #13's regression rider "
        "obliges a regression test that fails BEFORE the fix and passes AFTER when a "
        "root-cause capture documents a CODE defect (ADR-0067 D3)."
    ),
    "REG-003": (
        "Flaky tests are quarantined within 24 h by moving them to `tests/quarantine.txt`; "
        "quarantined tests have a 30-day SLA to be fixed or deleted; the golden-set "
        "critic-eval harness is retired (as amended by ADR-0081) — ADR-0067 D5 "
        "superseded, the D4 quarantine clause stands (ADR-0067 D4)."
    ),
    # -----------------------------------------------------------------------
    # glossary scope (ADR-0007, ADR-0012)
    # -----------------------------------------------------------------------
    # ADR-0007: glossary mechanism — D2 (entry shape) + D3 (scope rule) [D1+D5 superseded by ADR-0012]
    "GLO-001": (
        "Each glossary entry has a fixed shape: bold term, em-dash, one-sentence definition "
        "ending with a parenthetical citation of the ADR that introduces or owns the term "
        "(ADR-0007 D2)."
    ),
    "GLO-002": (
        "Three inclusion categories qualify for the glossary: (1) pipeline-stage names and "
        "their roles, (2) project-specific jargon that would confuse a new agent, and (3) "
        "terms whose usage is project-specific rather than standard; everyday English words "
        "do not qualify (ADR-0007 D3)."
    ),
    # ADR-0012: single-tier consolidation — D1 (CLAUDE.md only) + D2 (tightened threshold)
    "GLO-003": (
        "The glossary lives in a single tier: CLAUDE.md §4 (auto-loaded on every session); "
        "the separate long-tail glossary file (ADR-0007 D1) is retired; all entries must "
        "earn their place in the auto-loaded context (ADR-0012 D1)."
    ),
    "GLO-004": (
        "The glossary soft-cap is ~35 entries; new entries ride normal reviewer-gated PRs "
        "like any other CLAUDE.md edit, and the cap is mechanically enforced by the DOCS-9 "
        "health row — the dedicated add/fold skill and its critic bouncer are retired "
        "(as amended by ADR-0081) — while the tightened inclusion threshold stands "
        "(ADR-0012 D2/D5)."
    ),
}


def _get_rule_statement(rule_id: str, adr_id: str) -> str:
    """Return a one-line statement for the given rule_id."""
    if rule_id in _RULE_STATEMENTS:
        return _RULE_STATEMENTS[rule_id]
    # Fallback: generic statement referencing the source ADR
    return f"Rule {rule_id} sourced from {adr_id} — see ADR for details."


# ---------------------------------------------------------------------------
# Digest rendering
# ---------------------------------------------------------------------------

def _render_scope_rules(scope: str, adrs: list[dict]) -> str:
    """
    Render the rule-list body for the given scope + ADRs.

    This is shared between the AREA file renderer and the CLAUDE.md
    region renderer.  Returns the rule-list lines only (no file header,
    no paths: frontmatter — callers add those).
    """
    lines: list[str] = []
    lines.append(f"### {scope.capitalize()} rules\n")
    lines.append(
        f"Atomic rules for the `{scope}` scope, generated from non-superseded ADR "
        f"frontmatter by `tools/gen_rules.py`.\n"
    )
    for adr in adrs:
        adr_id = adr["id"]
        adr_file = adr["path"].name
        lines.append(f"\n#### Source: {adr_id} (`decisions/{adr_file}`)\n")
        for rule_id in adr["rule_ids"]:
            statement = _get_rule_statement(rule_id, adr_id)
            lines.append(f"- **{rule_id}:** {statement}\n")
    return "".join(lines)


def _render_scope(scope: str, adrs: list[dict]) -> str:
    """
    Render .claude/rules/<scope>.md content for an AREA scope.

    AREA files include:
      - The generated-file header comment
      - paths: YAML frontmatter (so Claude Code loads only when relevant)
      - The rule-list body
    """
    paths_val = SCOPE_PATHS.get(scope, "")
    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    # paths: frontmatter line (ADR-0073 D1 — area scopes must declare paths:)
    if paths_val:
        lines.append(f"paths: {paths_val}\n")
    lines.append("\n")
    lines.append(f"# {scope.capitalize()} rules\n")
    lines.append(
        f"Atomic rules for the `{scope}` scope, generated from non-superseded ADR "
        f"frontmatter by `tools/gen_rules.py`.\n"
    )
    for adr in adrs:
        adr_id = adr["id"]
        adr_file = adr["path"].name
        lines.append(f"\n## Source: {adr_id} (`decisions/{adr_file}`)\n")
        for rule_id in adr["rule_ids"]:
            statement = _get_rule_statement(rule_id, adr_id)
            lines.append(f"- **{rule_id}:** {statement}\n")
    return "".join(lines)


def _render_global_file(scopes_adrs: dict[str, list[dict]]) -> str:
    """
    Render all GLOBAL scope rules into .claude/generated/_global.md.

    This single file aggregates all 8 global scopes so CLAUDE.md can
    @import it with one line, keeping CLAUDE.md lean (<200 lines).
    Each scope is rendered as a named section.
    ADR-0073 D1: GLOBAL scopes are always-loaded via the @import mechanism.
    Lives in .claude/generated/ (not .claude/rules/) so the @import is the
    sole load path — no double-load (slice #945).
    """
    lines: list[str] = [GENERATED_HEADER, "\n"]
    lines.append("# Global rules (always-loaded)\n")
    lines.append(
        "All GLOBAL-scope atomic rules, generated from non-superseded ADR frontmatter"
        " by `tools/gen_rules.py`. Loaded into every Claude Code session via the"
        " `@.claude/generated/_global.md` import in CLAUDE.md (ADR-0073 D1)."
        " Lives outside .claude/rules/ so it is not also unconditionally"
        " auto-loaded (slice #945).\n"
    )
    for scope in sorted(scopes_adrs.keys()):
        lines.append("\n")
        lines.append(_render_scope_rules(scope, scopes_adrs[scope]))
    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _count_rule_ids(scopes: dict[str, list[dict]]) -> int:
    """
    Count the total number of rule_ids across all active scopes.

    Used by --check to report/verify conservation of rule_ids across
    relocation between CLAUDE.md and .claude/rules/ (ADR-0073 D5).
    """
    total = 0
    for scope_adrs in scopes.values():
        for adr in scope_adrs:
            total += len(adr.get("rule_ids", []))
    return total


def generate(check_mode: bool = False) -> int:
    """
    Generate (or diff-check) scope outputs per SCOPE_TARGET classification.

    GLOBAL scopes → .claude/generated/_global.md (@imported by CLAUDE.md;
                    NOT auto-loaded, so the @import is the sole load path).
    AREA scopes   → .claude/rules/<scope>.md (with paths: frontmatter).

    Args:
        check_mode: if True, compare fresh output to committed state and
                    exit non-zero if any differ (mirrors CHECK 2 behavior).
                    Also prints the total rule_id count for conservation checks.

    Returns exit code (0 = success, 1 = failure/dirty).
    """
    adrs = _load_adrs()

    # Separate into active (non-superseded) and superseded
    active_adrs = [a for a in adrs if not _is_superseded(a)]

    if not active_adrs:
        # An empty active-ADR set is never a legitimate no-op in this repo
        # (baseline is RULE_IDS_BASELINE rule_ids across dozens of ADRs) — it
        # is definitionally a broken checkout (missing/unreadable decisions/,
        # or frontmatter that stopped parsing). Fail loud rather than report
        # success while the entire generated-rule layer silently vanishes
        # (#1301).
        print(
            "gen_rules.py: FAIL — zero active ADRs with frontmatter found; "
            "this is treated as a broken checkout (missing/unreadable "
            "decisions/, or frontmatter parse failure), not a valid no-op. "
            "Refusing to leave stale generated output in place (#1301).",
            file=sys.stderr,
        )
        return 1

    # Group by scope
    scopes: dict[str, list[dict]] = {}
    for adr in active_adrs:
        scopes.setdefault(adr["scope"], []).append(adr)

    # Count rule_ids (conservation check — ADR-0073 D5)
    total_rule_ids = _count_rule_ids(scopes)
    print(f"gen_rules.py: total rule_ids across all active scopes: {total_rule_ids}")

    # Ensure .claude/rules/ and .claude/generated/ exist (unless check_mode)
    if not check_mode:
        RULES_DIR.mkdir(parents=True, exist_ok=True)
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    any_dirty = False
    generated_files: list[str] = []

    # Collect all GLOBAL scopes for aggregated _global.md rendering
    global_scopes: dict[str, list[dict]] = {
        scope: scope_adrs
        for scope, scope_adrs in sorted(scopes.items())
        if SCOPE_TARGET.get(scope, "area") == "global"
    }

    # --- GLOBAL scopes → .claude/generated/_global.md (single @import target,
    #     NOT auto-loaded — avoids the #945 double-load) ---
    if global_scopes:
        global_content = _render_global_file(global_scopes)

        if check_mode:
            if not GLOBAL_RULES_FILE.exists():
                print(
                    f"DIRTY: {GLOBAL_RULES_FILE.relative_to(REPO_ROOT)} does not exist "
                    f"(run 'python tools/gen_rules.py' and commit)",
                    file=sys.stderr,
                )
                any_dirty = True
            else:
                committed = GLOBAL_RULES_FILE.read_text(encoding="utf-8", errors="replace")
                if committed != global_content:
                    print(
                        f"DIRTY: {GLOBAL_RULES_FILE.relative_to(REPO_ROOT)} differs from "
                        f"fresh gen_rules.py output "
                        f"(run 'python tools/gen_rules.py' and commit)",
                        file=sys.stderr,
                    )
                    any_dirty = True
                else:
                    print(f"CLEAN: {GLOBAL_RULES_FILE.relative_to(REPO_ROOT)}")

            # Also verify CLAUDE.md contains the @import line
            try:
                claude_text = CLAUDE_MD.read_text(encoding="utf-8", errors="replace")
            except OSError:
                claude_text = ""
            if CLAUDE_MD_GLOBAL_IMPORT not in claude_text:
                print(
                    f"DIRTY: CLAUDE.md missing '@import' line '{CLAUDE_MD_GLOBAL_IMPORT}' "
                    f"(run 'python tools/gen_rules.py' and commit)",
                    file=sys.stderr,
                )
                any_dirty = True
            else:
                print(f"CLEAN: CLAUDE.md contains '{CLAUDE_MD_GLOBAL_IMPORT}'")
        else:
            changed = (
                not GLOBAL_RULES_FILE.exists()
                or GLOBAL_RULES_FILE.read_text(encoding="utf-8", errors="replace") != global_content
            )
            if changed:
                GLOBAL_RULES_FILE.write_text(global_content, encoding="utf-8")
                print(f"gen_rules.py: wrote {GLOBAL_RULES_FILE.relative_to(REPO_ROOT)}")
                generated_files.append(str(GLOBAL_RULES_FILE.relative_to(REPO_ROOT)))
            else:
                print(f"gen_rules.py: {GLOBAL_RULES_FILE.relative_to(REPO_ROOT)} already up-to-date")

    # --- AREA scopes → .claude/rules/<scope>.md (path-scoped, one per scope) ---
    for scope, scope_adrs in sorted(scopes.items()):
        if SCOPE_TARGET.get(scope, "area") != "area":
            continue

        content = _render_scope(scope, scope_adrs)
        out_path = RULES_DIR / f"{scope}.md"

        if check_mode:
            # Compare to committed file
            if not out_path.exists():
                print(
                    f"DIRTY: {out_path.relative_to(REPO_ROOT)} does not exist "
                    f"(run 'python tools/gen_rules.py' and commit)",
                    file=sys.stderr,
                )
                any_dirty = True
            else:
                committed = out_path.read_text(encoding="utf-8", errors="replace")
                if committed != content:
                    print(
                        f"DIRTY: {out_path.relative_to(REPO_ROOT)} differs from "
                        f"fresh gen_rules.py output "
                        f"(run 'python tools/gen_rules.py' and commit)",
                        file=sys.stderr,
                    )
                    any_dirty = True
                else:
                    print(f"CLEAN: {out_path.relative_to(REPO_ROOT)}")
        else:
            out_path.write_text(content, encoding="utf-8")
            rel = out_path.relative_to(REPO_ROOT)
            print(f"gen_rules.py: wrote {rel}")
            generated_files.append(str(rel))

    if check_mode:
        # Conservation check: live count must equal the migration baseline (ADR-0073 D5).
        # If it differs, either a new ADR was added (update RULE_IDS_BASELINE) or a rule
        # was silently removed — either way the mismatch is surfaced here.
        if total_rule_ids != RULE_IDS_BASELINE:
            print(
                f"CONSERVATION FAIL: rule_id count {total_rule_ids} != baseline "
                f"{RULE_IDS_BASELINE} — update RULE_IDS_BASELINE in gen_rules.py "
                f"after confirming no rules were lost (ADR-0073 D5)",
                file=sys.stderr,
            )
            any_dirty = True
        else:
            print(
                f"CONSERVATION OK: rule_ids total {total_rule_ids} == "
                f"baseline {RULE_IDS_BASELINE}"
            )
        if not any_dirty:
            print(f"gen_rules.py: all outputs clean (rule_ids total: {total_rule_ids})")
        return 1 if any_dirty else 0

    if not generated_files:
        print("gen_rules.py: nothing to write.", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    check = "--check" in sys.argv
    sys.exit(generate(check_mode=check))
