#!/usr/bin/env python3
"""Generate the declared D6 ship router; complete discovery is pending slice 1442."""
import argparse
import json
from pathlib import Path
import re
import subprocess

INVENTORY = ("ship",)
NOTICE = "D6 inventory: ship only; complete discovery pending slice #1442."


def repo_root() -> Path:
    result = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                            capture_output=True, text=True, encoding="utf-8", check=True)
    return Path(result.stdout.strip()).resolve()


def render(root: Path, name: str) -> str:
    source = root / ".claude" / "skills" / name / "SKILL.md"
    text = source.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(.*?)\n---\n", text, re.S)
    if not match:
        raise ValueError(f"missing discovery metadata: {source}")
    metadata = {}
    for line in match[1].splitlines():
        key, sep, value = line.partition(":")
        if sep:
            if key in metadata:
                raise ValueError(f"duplicate metadata: {key}")
            metadata[key] = value.strip().strip('"').strip("'")
    if metadata.get("name") != name or not metadata.get("description"):
        raise ValueError(f"invalid name/description: {source}")
    return (
        "---\nname: " + name + "\ndescription: " + json.dumps(metadata["description"])
        + "\n---\n\n<!-- Generated by tools/gen_openai_skills.py; do not edit. -->\n\n"
        "# Shared " + name + " workflow\n\n"
        "Read [AGENTS.md](../../../AGENTS.md) and "
        "[the OpenAI execution contract](../../../docs/openai-workflow.md).\n"
        "Then execute [the canonical procedure](../../../.claude/skills/" + name
        + "/SKILL.md) with that mapping. Do not copy or weaken its gates.\n\n"
        "Only the controller dispatches independent native workers. Use verified\n"
        "isolated worktrees, the host's configured model, and truthful identity.\n"
        "Apply the typed branch classifier before blind test-author dispatch.\n"
        "OpenAI QA and closure use tools/openai_workflow.py qa-verify and prd-close.\n"
        "Missing required capability or proof means a named handoff, never PASS.\n\n"
        + NOTICE + " Native hooks remain unverified in this slice.\n"
    )


def generate(root: Path, check: bool = False) -> bool:
    targets = {root / ".agents" / "skills" / name / "SKILL.md": render(root, name)
               for name in INVENTORY}
    actual = set((root / ".agents" / "skills").glob("*/SKILL.md"))
    extra = actual - targets.keys()
    if extra:
        raise ValueError("unexpected routers outside D6 inventory: "
                         + ", ".join(str(p.relative_to(root)) for p in sorted(extra)))
    clean = True
    for target, expected in targets.items():
        # Match the existing generators: Git's CRLF checkout is not content drift.
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            clean = False
            if check:
                print(f"stale: {target.relative_to(root)}")
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(expected.encode("utf-8"))
    print(NOTICE)
    return clean if check else True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        return 0 if generate(repo_root(), args.check) else 1
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print(f"router check refused: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
