#!/usr/bin/env python3
"""
tools/gen_repo_map.py — generate .claude/generated/_repo-map.md from filesystem.

Reuses the `dashboard/discovery.py` engine (same as `dashboard/readme_gen.py`) to emit
a repo-map table: one row per skill/agent/tool/dir with a link + short
description.  Delivered as an @import-ed file referenced by CLAUDE.md
(ADR-0073 D1 — generated-doc currency model).

Lives in .claude/generated/ (not .claude/rules/) so the CLAUDE.md @import
is the sole load path — .claude/rules/*.md files lacking a paths: key are
auto-loaded unconditionally by Claude Code, which would double-load this
file if it lived there (slice #945).

No LLM calls — pure stdlib + pathlib.

Usage:
  python tools/gen_repo_map.py          # writes .claude/generated/_repo-map.md
  python tools/gen_repo_map.py --check  # dry-run: exits non-zero if stale
"""

import os
import sys
from pathlib import Path
import subprocess

# ---------------------------------------------------------------------------
# Repo root resolution (mirrors gen_rules._resolve_repo_root)
# ---------------------------------------------------------------------------

def _resolve_repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=5, cwd=os.getcwd(),
        )
        if result.returncode == 0:
            root = Path(result.stdout.strip())
            if root.is_dir():
                return root
    except Exception:
        pass
    return Path(__file__).resolve().parent.parent


REPO_ROOT = _resolve_repo_root()
DASHBOARD_DIR = REPO_ROOT / "dashboard"
# .claude/generated/ (NOT .claude/rules/) — the latter is auto-loaded
# unconditionally by Claude Code for any *.md file lacking a paths: key,
# which would double-load this file alongside the CLAUDE.md @import (#945).
REPO_MAP_FILE = REPO_ROOT / ".claude" / "generated" / "_repo-map.md"

GENERATED_HEADER = (
    "<!-- GENERATED by tools/gen_repo_map.py — DO NOT EDIT —"
    " regenerate to update -->\n"
)
GENERATED_MARKER_BEGIN = "<!-- BEGIN GENERATED:repo-map -->"
GENERATED_MARKER_END   = "<!-- END GENERATED:repo-map -->"


def _inject_dashboard_path() -> None:
    """Inject dashboard/ into sys.path so discovery can be imported."""
    dashboard_str = str(DASHBOARD_DIR)
    if dashboard_str not in sys.path:
        sys.path.insert(0, dashboard_str)


# Lazy-import discovery functions; injected here so tests can monkeypatch them.
_inject_dashboard_path()
try:
    from discovery import discover_skills, discover_agents  # noqa: E402
except ImportError:
    # Fallback stubs (tests that patch these will still work)
    def discover_skills():  # type: ignore[misc]
        return []
    def discover_agents():  # type: ignore[misc]
        return []


def _build_repo_map() -> str:
    """Build the repo-map table using the `dashboard/discovery.py` engine."""
    skills = discover_skills()
    agents = discover_agents()

    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("\n")
    lines.append(GENERATED_MARKER_BEGIN + "\n")
    lines.append("# Repo map (generated)\n")
    lines.append(
        "Auto-generated map of skills, agents, tools, and key directories."
        " Generated by `tools/gen_repo_map.py` using the `dashboard/discovery.py`"
        " engine. Do not hand-edit — run the generator to update.\n\n"
    )

    # --- skills table ---
    lines.append("## Skills\n\n")
    lines.append("| Skill | Path | Description |\n")
    lines.append("|---|---|---|\n")
    for s in skills:
        name = s.get("name", "")
        path = s.get("path", "")
        desc = (s.get("description") or "").replace("|", "\\|")
        # Truncate description to keep table readable
        if len(desc) > 80:
            desc = desc[:77] + "..."
        lines.append(f"| `/{name}` | [`{path}`]({path}) | {desc} |\n")
    lines.append("\n")

    # --- agents table (critics + generators) ---
    lines.append("## Agents\n\n")
    lines.append("| Agent | Type | Path | Description |\n")
    lines.append("|---|---|---|---|\n")
    critics = [a for a in agents if a.get("type") == "critic"]
    generators = [a for a in agents if a.get("type") != "critic"]
    for a in critics + generators:
        name = a.get("name") or a.get("stem", "")
        kind = a.get("type", "")
        path = a.get("path", "")
        desc = (a.get("description") or "").replace("|", "\\|")
        if len(desc) > 80:
            desc = desc[:77] + "..."
        lines.append(f"| `{name}` | {kind} | [`{path}`]({path}) | {desc} |\n")
    lines.append("\n")

    # --- tools table ---
    lines.append("## Tools\n\n")
    lines.append("| Tool | Path | Description |\n")
    lines.append("|---|---|---|\n")
    _TOOLS = [
        ("gen_rules.py",   "tools/gen_rules.py",   "Generate global+area rules from ADR frontmatter"),
        ("gen_repo_map.py","tools/gen_repo_map.py", "Generate this repo-map file from filesystem"),
        ("pipeline_config.py","tools/pipeline_config.py",
         "Resolve the configured integration/release branch roles (ADR-0089 D1)"),
        ("ci-checks.sh",   "tools/ci-checks.sh",    "Deterministic CI gate (all project checks)"),
        ("worktree-guard.sh","tools/worktree-guard.sh","Worktree isolation guard; ff-restore + prune"),
        ("promote.sh",     "tools/promote.sh",      "Promote develop→main via RELEASE-READY gate"),
        ("check-slicer-provenance.py","tools/check-slicer-provenance.py",
         "Verify slicer-lane slice issues carry Slicer-provenance trailer (root-cause lane exempt)"),
        ("check-verdict-presence.py","tools/check-verdict-presence.py",
         "Verify recently-merged develop PRs carry a reviewer VERDICT: APPROVE comment"),
        ("release.py","tools/release.py",
         "Release-mode freeze/lanes/packet/verify (ADR-0090 D1/D3/D4)"),
    ]
    for tool_name, tool_path, tool_desc in _TOOLS:
        full_path = REPO_ROOT / tool_path
        if full_path.exists():
            lines.append(f"| `{tool_name}` | [`{tool_path}`]({tool_path}) | {tool_desc} |\n")
    lines.append("\n")

    # --- key dirs ---
    lines.append("## Key directories\n\n")
    lines.append("| Directory | Description |\n")
    lines.append("|---|---|\n")
    _DIRS = [
        ("decisions/",       "Architecture Decision Records (immutable, supersession-based)"),
        ("docs/decision-log/", "Dated per-problem records of operator decisions with ticked outcomes (append-only)"),
        (".claude/agents/",  "Subagent prompt files (critics + generators)"),
        (".claude/skills/",  "User-invocable skill prompt files"),
        (".claude/rules/",   "Generated AREA-scope rules (path-scoped, auto-loaded)"),
        (".claude/generated/", "Generated GLOBAL rules + repo-map (CLAUDE.md @import-only)"),
        (".claude/hooks/",   "Claude Code hook scripts"),
        ("dashboard/",       "CLI-only pipeline tooling: health checks, trace read-model, README generator (ADR-0088)"),
        ("tools/",           "CLI scripts for CI, generation, and promotion"),
        ("tests/",           "Regression test suite (pytest)"),
    ]
    for dir_path, dir_desc in _DIRS:
        lines.append(f"| [`{dir_path}`]({dir_path}) | {dir_desc} |\n")
    lines.append("\n")
    lines.append(GENERATED_MARKER_END + "\n")

    return "".join(lines)


def _count_table_rows(content: str) -> int:
    """Count data rows in all markdown tables in the content."""
    count = 0
    for line in content.splitlines():
        stripped = line.strip()
        # Table data rows: start with | but NOT a header separator (---|--- pattern)
        if stripped.startswith("|") and "---" not in stripped:
            # Skip header rows (usually right after the --- row)
            cells = [c.strip() for c in stripped.split("|") if c.strip()]
            if cells and not all(
                c.startswith(("**", "`", "Skill", "Agent", "Tool", "Directory",
                               "Type", "Path", "Description"))
                for c in cells
            ):
                count += 1
    return count


def generate(check_mode: bool = False) -> int:
    """
    Generate (or diff-check) .claude/generated/_repo-map.md.

    Args:
        check_mode: if True, compare fresh output to committed state and
                    exit non-zero if they differ.

    Returns exit code (0 = success / clean, 1 = failure / dirty).
    """
    content = _build_repo_map()

    # Count rows for AC verification
    row_count = _count_table_rows(content)
    print(f"gen_repo_map.py: repo-map table rows: {row_count}")

    try:
        rel_path = REPO_MAP_FILE.relative_to(REPO_ROOT)
    except ValueError:
        rel_path = REPO_MAP_FILE  # temp dir in tests — show full path

    if check_mode:
        if not REPO_MAP_FILE.exists():
            print(
                f"DIRTY: {rel_path} does not exist "
                f"(run 'python tools/gen_repo_map.py' and commit)",
                file=sys.stderr,
            )
            return 1
        committed = REPO_MAP_FILE.read_text(encoding="utf-8", errors="replace")
        if committed != content:
            print(
                f"DIRTY: {rel_path} differs from "
                f"fresh gen_repo_map.py output "
                f"(run 'python tools/gen_repo_map.py' and commit)",
                file=sys.stderr,
            )
            return 1
        print(f"CLEAN: {rel_path} (rows: {row_count})")
        return 0

    REPO_MAP_FILE.parent.mkdir(parents=True, exist_ok=True)
    changed = (
        not REPO_MAP_FILE.exists()
        or REPO_MAP_FILE.read_text(encoding="utf-8", errors="replace") != content
    )
    try:
        rel_path = REPO_MAP_FILE.relative_to(REPO_ROOT)
    except ValueError:
        rel_path = REPO_MAP_FILE  # temp dir in tests — show full path
    if changed:
        REPO_MAP_FILE.write_text(content, encoding="utf-8")
        print(f"gen_repo_map.py: wrote {rel_path} ({row_count} table rows)")
    else:
        print(f"gen_repo_map.py: {rel_path} already up-to-date ({row_count} table rows)")
    return 0


if __name__ == "__main__":
    check = "--check" in sys.argv
    sys.exit(generate(check_mode=check))
